/**
 * WP-82 — Le Cahier follows the one language rule.
 *
 * The Cahier's own words — tab labels, filters, counts, section heads, the
 * notes bar, the journal's instructions and verdicts, the library runner, the
 * word biography's ledger, the fragility chip — are chrome: up to A2 they are
 * the learner's language, from B1 they are French (`chromeLanguage`,
 * `lib/language-rule.ts`). What arrives from the server as learner material
 * (a rule, an example, a trap, a scene, the learner's own text, a concept's
 * French title and category) is content and stays French whatever this table
 * says. Place names (Le Cahier, Relevé, Bibliothèque, Lexique, L’Atelier, Le
 * Feuilleton, Le Courrier, Le Studio, L’Épreuve) are French in every column.
 *
 * One module for the whole cluster, grouped by screen: `cahier` (the shared
 * head and pill in CahierV2), `notes` (the margin notes, shared by the grammar
 * fiche and the legacy Cahiers kit), `grammar`, `notebook` (the /notebook
 * shell), `library`, `journal`, `legacy` (components/cahiers/Cahiers.tsx),
 * `biography` (the word biography sheet) and `fragility` (the badge).
 *
 * Every table has the same keys and the same `{placeholders}` (the copy test
 * proves it). The French column keeps the wording these screens always had.
 */

import { useControlLanguage } from '@/components/atelier-v2/ui';
import { normalizeControlLanguage } from '@/lib/atelier-v2-copy';
import type { ControlLanguage } from '@/types/daily-journey';

const FR = {
  cahier: {
    locale: 'fr-FR',
    retry: 'Réessayer',
    mode_grammar: 'Règles',
    mode_vocabulary: 'Mots',
    mode_journal: 'Journal',
    mode_releve: 'Relevé',
    mode_library: 'Livres',
    modes_label: 'Rubriques du cahier',
    filter: 'Filtrer',
    clear_filters: 'Effacer les filtres',
    concepts_one: '{n} concept',
    concepts_many: '{n} concepts',
    seen_one: '{n} vu',
    seen_many: '{n} vus',
    feuilleton_filed: 'Le feuilleton · classé au dossier',
    episode_prefix: 'Épisode {n} — ',
  },
  notes: {
    title: 'Notes en marge',
    empty: 'Aucune note pour l’instant — la marge vous attend.',
    edit: 'Modifier',
    annotate: 'Annoter',
    saved: 'Enregistrée',
    save: 'Enregistrer',
    sending: 'Envoi…',
    cancel: 'Annuler',
    state_failed: 'Échec — note conservée ici',
    state_saving: 'Classement en cours',
    state_dirty: 'Non enregistrée',
    state_draft: 'Brouillon',
    failed: 'La note n’a pas pu être classée. Elle reste dans la marge.',
    toast_saved: 'Note classée.',
    toast_failed: 'La note n’a pas pu être classée.',
  },
  grammar: {
    page_title: 'Le Cahier · Grammaire · L’Atelier',
    page_label: 'Le cahier · Règles',
    kicker_loading: 'Les règles',
    chip_all: 'Tous',
    chip_due: 'À revoir',
    live_loading: 'Classement en cours…',
    sheets_one: '{n} fiche',
    sheets_many: '{n} fiches',
    sheets_due_one: '{n} fiche à revoir',
    sheets_due_many: '{n} fiches à revoir',
    recent_errata_one: '{n} errata récent',
    recent_errata_many: '{n} errata récents',
    search: 'Chercher une règle, un piège…',
    filter_label: 'Filtrer les règles',
    index_failed_title: 'L’index des règles n’a pas pu être ouvert',
    index_failed_body: 'Vos fiches sont en sûreté ; réessayez dans un instant.',
    loading: 'Classement en cours',
    index_label: 'Index des règles',
    index_back_n: 'Index des règles · fiche {n}',
    meta_due: 'à revoir',
    meta_errata: '{n} errata',
    row_aria: '{title}, {level} {category}, maîtrise {mastery} sur 10',
    row_aria_due: '{title}, {level} {category}, maîtrise {mastery} sur 10, à revoir',
    empty_filtered: 'Aucune fiche ne correspond à ce filtre',
    empty_title: 'Le cahier s’ouvre à la première séance',
    empty_body: 'Vos fiches de grammaire se classent ici dès que l’Atelier compose votre première page.',
    open_atelier: 'Ouvrir l’Atelier',
    fiche_failed_title: 'Cette fiche n’a pas pu être ouverte',
    fiche_failed_body: 'Votre index reste consultable.',
    fiche_loading: 'Ouverture de la fiche',
    fiche_label: 'Fiche de grammaire',
    mastery: 'Maîtrise',
    next_review: 'Prochaine révision · {date}',
    sec_rule: 'La règle',
    sec_examples: 'Exemples d’ancrage',
    examples_one: '{n} exemple',
    examples_many: '{n} exemples',
    sec_traps: 'Pièges principaux',
    traps_one: '{n} relevé',
    traps_many: '{n} relevés',
    sec_pattern: 'Motif',
    sec_due_errata: 'Errata à revoir',
    due_one: '{n} dû',
    due_many: '{n} dus',
    sec_recent_errata: 'Errata récents',
    repaired_one: '{n} réparé',
    repaired_many: '{n} réparés',
    cta: 'Travailler cette règle à l’Atelier',
  },
  notebook: {
    title_grammar: 'Le Cahier · Grammaire',
    title_vocabulary: 'Le Cahier · Lexique',
    title_journal: 'Le Cahier · Le journal de bord',
    title_releve: 'Le Cahier · Le Relevé',
    title_library: 'Le Cahier · Bibliothèque',
    feuilleton_fallback: 'Reprendre le feuilleton',
    cefr_line: '{level} en cours',
  },
  library: {
    comprehension: 'Compréhension',
    comprehension_title: 'Retrouver la preuve {n}',
    comprehension_prompt: 'Répondez à partir du passage.',
    lexique: 'Lexique',
    word_title: 'Mot {n}',
    vocabulary_prompt: 'Quel mot du passage convient ici ? {hint}',
    vocabulary_hint: 'Appuyez-vous sur la phrase.',
    grammar: 'Grammaire dans le passage',
    grammar_title: 'Structure',
    grammar_prompt: 'Repérez la structure dans le passage.',
    production: 'Production',
    production_title: 'Écrire depuis le passage',
    production_prompt: 'Écrivez une réponse courte appuyée sur le passage.',
    ready: 'Prêt à classer',
    verified: 'Vérifié dans le passage',
    ready_body: 'La réponse est assez développée pour faire avancer l’épisode. Gardez un détail du passage visible.',
    verified_body: 'Bien. La réponse s’appuie sur un élément précis du passage.',
    evidence: 'Preuve : {text}',
    wrong_title: 'Le passage fait foi',
    wrong_vocabulary: 'Relisez la phrase de contexte et reprenez le mot correspondant à l’indice.',
    wrong_other: 'Ajoutez un détail concret du passage avant de continuer.',
    target: 'Réponse visée : {text}',
    load_failed: 'La bibliothèque n’a pas pu être chargée.',
    loading: 'Ouverture de la bibliothèque',
    empty_body: 'Vos livres importés paraîtront ici sous forme d’épisodes de lecture.',
    open_imports: 'Ouvrir les imports',
    books_label: 'Livres importés',
    imported_text: 'Texte importé',
    open_marker: 'ouvert',
    reader_label: 'Épisode de lecture sélectionné',
    episode_loading: 'Ouverture de l’épisode',
    episode_meta: 'Épisode {n} sur {total} · {minutes} min · {words} mots',
    done_label: 'Exercices de l’épisode terminés',
    done_kicker: 'Exercices classés',
    done_title: 'L’épisode {n} est terminé.',
    done_body: 'Le passage, le lexique et la consigne de production sont classés dans votre progression.',
    ready_label: 'Épisode prêt à être classé',
    ready_kicker: 'Moment de bilan',
    ready_title: 'Prêt à continuer {title}',
    ready_summary: 'Vous avez lu le passage, vérifié les consignes et écrit depuis l’épisode.',
    finishing: 'Classement…',
    finish: 'Terminer l’épisode',
    exercise_n: 'Exercice {n} sur {total}',
    progress_label: 'Progression des exercices',
    line_placeholder: 'Répondez à partir du passage',
    paragraph_placeholder: 'Écrivez votre réponse en français',
    check: 'Vérifier',
    preview_label: 'Exercices de l’épisode',
    preview_title: 'Consignes de l’épisode',
  },
  journal: {
    yesterday: 'Hier',
    days_ago: 'Il y a {n} jours',
    with: 'avec {name}',
    recall_unscored: 'Cette scène n’a rien de noté à retrouver : rien à vérifier ici.',
    recall_all: 'Vous avez retrouvé tout ce que la scène avait retenu ({found}/{total}).',
    recall_none: 'Rien de ce que la scène avait retenu n’apparaît (0/{total}).',
    recall_some: 'Vous avez retrouvé {found} élément(s) sur {total}.',
    correction_unavailable: 'La correction n’a pas pu être faite. Votre texte est gardé tel quel.',
    correction_clean: 'Rien à corriger dans ce texte.',
    correction_one: 'Une chose à revoir.',
    correction_many: '{n} choses à revoir.',
    send_failed: 'L’entrée n’a pas pu être envoyée. Réessayez.',
    busy_failed: 'Impossible pour l’instant. Réessayez.',
    load_failed_title: 'Le journal n’a pas pu être ouvert',
    load_failed_body: 'La connexion a échoué. Rien n’est perdu.',
    followup_kicker: 'Une semaine plus tard',
    followup_label: 'Votre réponse, en une phrase',
    followup_placeholder: 'Une phrase suffit.',
    sending: 'Envoi…',
    reply: 'Répondre',
    empty_title: 'Rien à raconter aujourd’hui',
    empty_body: 'Le journal s’ouvre le lendemain d’une scène. Revenez demain.',
    skipped_title: 'Entrée passée',
    skipped_body: 'Cette scène ne sera plus proposée. La prochaine arrivera demain.',
    headline: 'Le journal de bord',
    cue_fallback: 'La scène d’hier',
    field_label: 'Hier, en français',
    hint: 'Une seule correction en avant, la liste complète sur demande. Dans une semaine, une ligne vous redemandera cette scène.',
    word_count: '{n} mot(s) · {min} au minimum',
    correcting: 'Correction en cours…',
    send: 'Envoyer',
    foot_note: 'Relire la scène après l’envoi',
    skip: 'Passer cette scène',
    entry_fallback: 'Votre entrée',
    french_label: 'Le français',
    hide_detail: 'Masquer le détail',
    show_all: 'Tout voir',
    errata_one: 'Une faute est notée au Relevé et reviendra dans une scène.',
    errata_many: '{n} fautes sont notées au Relevé et reviendront dans une scène.',
    recall_label: 'Ce dont vous vous souvenez',
    recall_empty: 'Rien à vérifier ici.',
    reveal_label: 'La scène, telle qu’elle était',
  },
  legacy: {
    course: 'Cours · {level}',
    progress_unavailable: 'Progression indisponible',
    settings: 'Réglages',
    tab_grammar: 'Grammaire',
    tab_vocabulary: 'Vocabulaire',
    modes_label: 'Modes du carnet',
    resume: 'Reprendre →',
    filters: 'Filtres',
    due: 'À revoir',
    due_suffix: ', à revoir',
    state_new: 'Nouveau',
    errata: '{n} errata',
    mastery: 'Maîtrise {n} sur 10',
    notice_label: 'Avis du bureau des archives',
    map_legend: 'Répartition des états',
    empty_title: 'Aucune fiche dans ce classement',
    colophon: 'Les Cahiers · référence de l’édition',
  },
  biography: {
    no_date: 'Sans date',
    source_anki_deck: 'Paquet importé',
    source_deck: 'Paquet',
    source_errata: 'Errata',
    source_review: 'Révision',
    source_pilot_capture: 'Capture pilote',
    examples: 'Exemples',
    title_fallback: 'Le fil du mot',
    eyebrow: 'L’histoire du mot',
    opening: 'Ouverture…',
    loading: 'Ouverture de l’histoire…',
    failed: 'L’histoire est indisponible.',
    ledger_label: 'État de la mémoire',
    tile_state: 'État',
    tile_seen: 'Vu',
    tile_used: 'Employé',
    tile_errata: 'Errata',
    thread: 'Le fil',
    no_trace: 'Ce mot n’a pas encore laissé de trace.',
  },
  fragility: {
    new: 'Nouveau',
    new_reason_unseen: 'Pas encore révisé par vous.',
    new_reason: 'Pas encore révisé.',
    due: 'À revoir',
    due_reason: 'Prêt pour une reprise.',
    fraying: 'Mémoire qui s’effrite',
    fraying_reason: 'Plusieurs oublis, ou un rappel estimé faible.',
    tender: 'Mémoire fragile',
    tender_reason: 'Utile, mais encore facile à perdre.',
    holding: 'Tient',
    holding_reason: 'Ce fil tient bien pour l’instant.',
    forming: 'En formation',
    forming_reason: 'Le fil se dessine.',
  },
};

export type CahierCopy = typeof FR;

const EN: CahierCopy = {
  cahier: {
    locale: 'en-GB',
    retry: 'Try again',
    mode_grammar: 'Rules',
    mode_vocabulary: 'Words',
    mode_journal: 'Journal',
    mode_releve: 'Relevé',
    mode_library: 'Books',
    modes_label: 'Notebook sections',
    filter: 'Filter',
    clear_filters: 'Clear filters',
    concepts_one: '{n} concept',
    concepts_many: '{n} concepts',
    seen_one: '{n} seen',
    seen_many: '{n} seen',
    feuilleton_filed: 'Le Feuilleton · filed in your notebook',
    episode_prefix: 'Episode {n} — ',
  },
  notes: {
    title: 'Margin notes',
    empty: 'No notes yet — the margin is yours.',
    edit: 'Edit',
    annotate: 'Add a note',
    saved: 'Saved',
    save: 'Save',
    sending: 'Saving…',
    cancel: 'Cancel',
    state_failed: 'Failed — your note is kept here',
    state_saving: 'Saving',
    state_dirty: 'Not saved',
    state_draft: 'Draft',
    failed: 'The note could not be saved. It stays in the margin.',
    toast_saved: 'Note saved.',
    toast_failed: 'The note could not be saved.',
  },
  grammar: {
    page_title: 'Le Cahier · Grammar · L’Atelier',
    page_label: 'Le Cahier · Rules',
    kicker_loading: 'The rules',
    chip_all: 'All',
    chip_due: 'To review',
    live_loading: 'Sorting…',
    sheets_one: '{n} rule card',
    sheets_many: '{n} rule cards',
    sheets_due_one: '{n} rule card to review',
    sheets_due_many: '{n} rule cards to review',
    recent_errata_one: '{n} recent mistake',
    recent_errata_many: '{n} recent mistakes',
    search: 'Search for a rule or a trap…',
    filter_label: 'Filter the rules',
    index_failed_title: 'The rule index could not be opened',
    index_failed_body: 'Your rule cards are safe; try again in a moment.',
    loading: 'Sorting',
    index_label: 'Rule index',
    index_back_n: 'Rule index · card {n}',
    meta_due: 'to review',
    meta_errata: '{n} mistakes',
    row_aria: '{title}, {level} {category}, mastery {mastery} out of 10',
    row_aria_due: '{title}, {level} {category}, mastery {mastery} out of 10, to review',
    empty_filtered: 'No rule card matches this filter',
    empty_title: 'Your notebook opens with your first session',
    empty_body: 'Your grammar cards are filed here as soon as L’Atelier writes your first page.',
    open_atelier: 'Open L’Atelier',
    fiche_failed_title: 'This rule card could not be opened',
    fiche_failed_body: 'Your index is still available.',
    fiche_loading: 'Opening the rule card',
    fiche_label: 'Grammar card',
    mastery: 'Mastery',
    next_review: 'Next review · {date}',
    sec_rule: 'The rule',
    sec_examples: 'Anchor examples',
    examples_one: '{n} example',
    examples_many: '{n} examples',
    sec_traps: 'Main traps',
    traps_one: '{n} noted',
    traps_many: '{n} noted',
    sec_pattern: 'Pattern',
    sec_due_errata: 'Mistakes to review',
    due_one: '{n} due',
    due_many: '{n} due',
    sec_recent_errata: 'Recent mistakes',
    repaired_one: '{n} fixed',
    repaired_many: '{n} fixed',
    cta: 'Practise this rule in L’Atelier',
  },
  notebook: {
    title_grammar: 'Le Cahier · Grammar',
    title_vocabulary: 'Le Cahier · Lexique',
    title_journal: 'Le Cahier · Logbook',
    title_releve: 'Le Cahier · Le Relevé',
    title_library: 'Le Cahier · Bibliothèque',
    feuilleton_fallback: 'Continue Le Feuilleton',
    cefr_line: '{level} in progress',
  },
  library: {
    comprehension: 'Comprehension',
    comprehension_title: 'Find the evidence {n}',
    comprehension_prompt: 'Answer from the passage.',
    lexique: 'Lexique',
    word_title: 'Word {n}',
    vocabulary_prompt: 'Which word from the passage fits here? {hint}',
    vocabulary_hint: 'Use the sentence as your guide.',
    grammar: 'Grammar in the passage',
    grammar_title: 'Structure',
    grammar_prompt: 'Find the structure in the passage.',
    production: 'Writing',
    production_title: 'Write from the passage',
    production_prompt: 'Write a short answer based on the passage.',
    ready: 'Ready to file',
    verified: 'Checked against the passage',
    ready_body: 'Your answer is developed enough to move the episode on. Keep one detail from the passage in view.',
    verified_body: 'Good. Your answer rests on a precise detail from the passage.',
    evidence: 'Evidence: {text}',
    wrong_title: 'The passage decides',
    wrong_vocabulary: 'Reread the context sentence and pick the word that matches the hint.',
    wrong_other: 'Add a concrete detail from the passage before you continue.',
    target: 'Expected answer: {text}',
    load_failed: 'The library could not be loaded.',
    loading: 'Opening the library',
    empty_body: 'Your imported books will appear here as reading episodes.',
    open_imports: 'Open imports',
    books_label: 'Imported books',
    imported_text: 'Imported text',
    open_marker: 'open',
    reader_label: 'Selected reading episode',
    episode_loading: 'Opening the episode',
    episode_meta: 'Episode {n} of {total} · {minutes} min · {words} words',
    done_label: 'Episode exercises finished',
    done_kicker: 'Exercises filed',
    done_title: 'Episode {n} is finished.',
    done_body: 'The passage, the vocabulary and the writing task are filed in your progress.',
    ready_label: 'Episode ready to file',
    ready_kicker: 'Time to wrap up',
    ready_title: 'Ready to continue {title}',
    ready_summary: 'You read the passage, checked the tasks and wrote from the episode.',
    finishing: 'Filing…',
    finish: 'Finish the episode',
    exercise_n: 'Exercise {n} of {total}',
    progress_label: 'Exercise progress',
    line_placeholder: 'Answer from the passage',
    paragraph_placeholder: 'Write your answer in French',
    check: 'Check',
    preview_label: 'Episode exercises',
    preview_title: 'Episode tasks',
  },
  journal: {
    yesterday: 'Yesterday',
    days_ago: '{n} days ago',
    with: 'with {name}',
    recall_unscored: 'This scene has nothing noted to recall, so there is nothing to check here.',
    recall_all: 'You recalled everything the scene kept ({found}/{total}).',
    recall_none: 'None of what the scene kept appears (0/{total}).',
    recall_some: 'You recalled {found} of {total} details.',
    correction_unavailable: 'The correction could not be made. Your text is kept as it is.',
    correction_clean: 'Nothing to correct in this text.',
    correction_one: 'One thing to review.',
    correction_many: '{n} things to review.',
    send_failed: 'The entry could not be sent. Try again.',
    busy_failed: 'Not possible right now. Try again.',
    load_failed_title: 'The journal could not be opened',
    load_failed_body: 'The connection failed. Nothing is lost.',
    followup_kicker: 'One week later',
    followup_label: 'Your answer, in one sentence',
    followup_placeholder: 'One sentence is enough.',
    sending: 'Sending…',
    reply: 'Reply',
    empty_title: 'Nothing to tell today',
    empty_body: 'The journal opens the day after a scene. Come back tomorrow.',
    skipped_title: 'Entry skipped',
    skipped_body: 'This scene will not come back. The next one arrives tomorrow.',
    headline: 'The logbook',
    cue_fallback: 'Yesterday’s scene',
    field_label: 'Yesterday, in French',
    hint: 'One correction up front, the full list on request. In a week, one line will ask you about this scene again.',
    word_count: '{n} word(s) · {min} minimum',
    correcting: 'Correcting…',
    send: 'Send',
    foot_note: 'Reread the scene after sending',
    skip: 'Skip this scene',
    entry_fallback: 'Your entry',
    french_label: 'Your French',
    hide_detail: 'Hide the details',
    show_all: 'See all',
    errata_one: 'One mistake is noted in Le Relevé and will come back in a scene.',
    errata_many: '{n} mistakes are noted in Le Relevé and will come back in a scene.',
    recall_label: 'What you remember',
    recall_empty: 'Nothing to check here.',
    reveal_label: 'The scene as it was',
  },
  legacy: {
    course: 'Course · {level}',
    progress_unavailable: 'Progress unavailable',
    settings: 'Settings',
    tab_grammar: 'Grammar',
    tab_vocabulary: 'Vocabulary',
    modes_label: 'Notebook modes',
    resume: 'Continue →',
    filters: 'Filters',
    due: 'To review',
    due_suffix: ', to review',
    state_new: 'New',
    errata: '{n} mistakes',
    mastery: 'Mastery {n} out of 10',
    notice_label: 'Notice from the archive',
    map_legend: 'Breakdown by state',
    empty_title: 'No card in this view',
    colophon: 'Les Cahiers · reference edition',
  },
  biography: {
    no_date: 'No date',
    source_anki_deck: 'Imported deck',
    source_deck: 'Deck',
    source_errata: 'Mistakes',
    source_review: 'Review',
    source_pilot_capture: 'Pilot capture',
    examples: 'Examples',
    title_fallback: 'The word’s thread',
    eyebrow: 'The word’s story',
    opening: 'Opening…',
    loading: 'Opening the story…',
    failed: 'The story is unavailable.',
    ledger_label: 'Memory state',
    tile_state: 'State',
    tile_seen: 'Seen',
    tile_used: 'Used',
    tile_errata: 'Mistakes',
    thread: 'The thread',
    no_trace: 'This word has not left a trace yet.',
  },
  fragility: {
    new: 'New',
    new_reason_unseen: 'You have not reviewed it yet.',
    new_reason: 'Not reviewed yet.',
    due: 'To review',
    due_reason: 'Ready for a review.',
    fraying: 'Memory fading',
    fraying_reason: 'Forgotten several times, or recall estimated low.',
    tender: 'Fragile memory',
    tender_reason: 'Useful, but still easy to lose.',
    holding: 'Holding',
    holding_reason: 'This thread holds well for now.',
    forming: 'Forming',
    forming_reason: 'The thread is taking shape.',
  },
};

const DE: CahierCopy = {
  cahier: {
    locale: 'de-DE',
    retry: 'Erneut versuchen',
    mode_grammar: 'Regeln',
    mode_vocabulary: 'Wörter',
    mode_journal: 'Journal',
    mode_releve: 'Relevé',
    mode_library: 'Bücher',
    modes_label: 'Bereiche des Hefts',
    filter: 'Filtern',
    clear_filters: 'Filter zurücksetzen',
    concepts_one: '{n} Konzept',
    concepts_many: '{n} Konzepte',
    seen_one: '{n} gesehen',
    seen_many: '{n} gesehen',
    feuilleton_filed: 'Le Feuilleton · in Ihrem Heft abgelegt',
    episode_prefix: 'Folge {n} — ',
  },
  notes: {
    title: 'Randnotizen',
    empty: 'Noch keine Notiz — der Rand gehört Ihnen.',
    edit: 'Bearbeiten',
    annotate: 'Notiz hinzufügen',
    saved: 'Gespeichert',
    save: 'Speichern',
    sending: 'Speichern…',
    cancel: 'Abbrechen',
    state_failed: 'Fehlgeschlagen — Notiz bleibt hier',
    state_saving: 'Wird gespeichert',
    state_dirty: 'Nicht gespeichert',
    state_draft: 'Entwurf',
    failed: 'Die Notiz konnte nicht gespeichert werden. Sie bleibt am Rand.',
    toast_saved: 'Notiz gespeichert.',
    toast_failed: 'Die Notiz konnte nicht gespeichert werden.',
  },
  grammar: {
    page_title: 'Le Cahier · Grammatik · L’Atelier',
    page_label: 'Le Cahier · Regeln',
    kicker_loading: 'Die Regeln',
    chip_all: 'Alle',
    chip_due: 'Zu wiederholen',
    live_loading: 'Wird sortiert…',
    sheets_one: '{n} Regelkarte',
    sheets_many: '{n} Regelkarten',
    sheets_due_one: '{n} Regelkarte zu wiederholen',
    sheets_due_many: '{n} Regelkarten zu wiederholen',
    recent_errata_one: '{n} neuer Fehler',
    recent_errata_many: '{n} neue Fehler',
    search: 'Regel oder Stolperfalle suchen…',
    filter_label: 'Regeln filtern',
    index_failed_title: 'Das Regelverzeichnis konnte nicht geöffnet werden',
    index_failed_body: 'Ihre Regelkarten sind sicher; versuchen Sie es gleich noch einmal.',
    loading: 'Wird sortiert',
    index_label: 'Regelverzeichnis',
    index_back_n: 'Regelverzeichnis · Karte {n}',
    meta_due: 'zu wiederholen',
    meta_errata: '{n} Fehler',
    row_aria: '{title}, {level} {category}, Beherrschung {mastery} von 10',
    row_aria_due: '{title}, {level} {category}, Beherrschung {mastery} von 10, zu wiederholen',
    empty_filtered: 'Keine Regelkarte passt zu diesem Filter',
    empty_title: 'Ihr Heft öffnet sich mit der ersten Sitzung',
    empty_body: 'Ihre Grammatikkarten werden hier abgelegt, sobald L’Atelier Ihre erste Seite schreibt.',
    open_atelier: 'L’Atelier öffnen',
    fiche_failed_title: 'Diese Regelkarte konnte nicht geöffnet werden',
    fiche_failed_body: 'Ihr Verzeichnis bleibt verfügbar.',
    fiche_loading: 'Regelkarte wird geöffnet',
    fiche_label: 'Grammatikkarte',
    mastery: 'Beherrschung',
    next_review: 'Nächste Wiederholung · {date}',
    sec_rule: 'Die Regel',
    sec_examples: 'Ankerbeispiele',
    examples_one: '{n} Beispiel',
    examples_many: '{n} Beispiele',
    sec_traps: 'Häufige Stolperfallen',
    traps_one: '{n} notiert',
    traps_many: '{n} notiert',
    sec_pattern: 'Muster',
    sec_due_errata: 'Fehler zum Wiederholen',
    due_one: '{n} fällig',
    due_many: '{n} fällig',
    sec_recent_errata: 'Neue Fehler',
    repaired_one: '{n} behoben',
    repaired_many: '{n} behoben',
    cta: 'Diese Regel in L’Atelier üben',
  },
  notebook: {
    title_grammar: 'Le Cahier · Grammatik',
    title_vocabulary: 'Le Cahier · Lexique',
    title_journal: 'Le Cahier · Logbuch',
    title_releve: 'Le Cahier · Le Relevé',
    title_library: 'Le Cahier · Bibliothèque',
    feuilleton_fallback: 'Le Feuilleton fortsetzen',
    cefr_line: '{level} in Arbeit',
  },
  library: {
    comprehension: 'Textverständnis',
    comprehension_title: 'Beleg {n} finden',
    comprehension_prompt: 'Antworten Sie anhand des Textes.',
    lexique: 'Lexique',
    word_title: 'Wort {n}',
    vocabulary_prompt: 'Welches Wort aus dem Text passt hier? {hint}',
    vocabulary_hint: 'Orientieren Sie sich am Satz.',
    grammar: 'Grammatik im Text',
    grammar_title: 'Struktur',
    grammar_prompt: 'Finden Sie die Struktur im Text.',
    production: 'Schreiben',
    production_title: 'Aus dem Text schreiben',
    production_prompt: 'Schreiben Sie eine kurze Antwort, gestützt auf den Text.',
    ready: 'Bereit zum Ablegen',
    verified: 'Am Text geprüft',
    ready_body: 'Ihre Antwort ist ausführlich genug, um die Folge voranzubringen. Behalten Sie ein Detail aus dem Text im Blick.',
    verified_body: 'Gut. Ihre Antwort stützt sich auf ein genaues Detail aus dem Text.',
    evidence: 'Beleg: {text}',
    wrong_title: 'Der Text entscheidet',
    wrong_vocabulary: 'Lesen Sie den Kontextsatz noch einmal und nehmen Sie das Wort, das zum Hinweis passt.',
    wrong_other: 'Ergänzen Sie ein konkretes Detail aus dem Text, bevor Sie weitermachen.',
    target: 'Erwartete Antwort: {text}',
    load_failed: 'Die Bibliothek konnte nicht geladen werden.',
    loading: 'Bibliothek wird geöffnet',
    empty_body: 'Ihre importierten Bücher erscheinen hier als Lesefolgen.',
    open_imports: 'Importe öffnen',
    books_label: 'Importierte Bücher',
    imported_text: 'Importierter Text',
    open_marker: 'geöffnet',
    reader_label: 'Ausgewählte Lesefolge',
    episode_loading: 'Folge wird geöffnet',
    episode_meta: 'Folge {n} von {total} · {minutes} Min. · {words} Wörter',
    done_label: 'Übungen der Folge abgeschlossen',
    done_kicker: 'Übungen abgelegt',
    done_title: 'Folge {n} ist abgeschlossen.',
    done_body: 'Der Text, der Wortschatz und die Schreibaufgabe sind in Ihrem Fortschritt abgelegt.',
    ready_label: 'Folge bereit zum Ablegen',
    ready_kicker: 'Zeit für eine Bilanz',
    ready_title: 'Bereit, {title} fortzusetzen',
    ready_summary: 'Sie haben den Text gelesen, die Aufgaben geprüft und aus der Folge heraus geschrieben.',
    finishing: 'Wird abgelegt…',
    finish: 'Folge abschließen',
    exercise_n: 'Übung {n} von {total}',
    progress_label: 'Fortschritt der Übungen',
    line_placeholder: 'Antworten Sie anhand des Textes',
    paragraph_placeholder: 'Schreiben Sie Ihre Antwort auf Französisch',
    check: 'Prüfen',
    preview_label: 'Übungen der Folge',
    preview_title: 'Aufgaben der Folge',
  },
  journal: {
    yesterday: 'Gestern',
    days_ago: 'Vor {n} Tagen',
    with: 'mit {name}',
    recall_unscored: 'In dieser Szene gibt es nichts Festgehaltenes zu erinnern, also nichts zu prüfen.',
    recall_all: 'Sie haben alles wiedergefunden, was die Szene festhielt ({found}/{total}).',
    recall_none: 'Nichts von dem, was die Szene festhielt, taucht auf (0/{total}).',
    recall_some: 'Sie haben {found} von {total} Details wiedergefunden.',
    correction_unavailable: 'Die Korrektur war nicht möglich. Ihr Text bleibt, wie er ist.',
    correction_clean: 'Nichts zu korrigieren in diesem Text.',
    correction_one: 'Eine Sache zum Wiederholen.',
    correction_many: '{n} Dinge zum Wiederholen.',
    send_failed: 'Der Eintrag konnte nicht gesendet werden. Bitte erneut versuchen.',
    busy_failed: 'Im Moment nicht möglich. Bitte erneut versuchen.',
    load_failed_title: 'Das Journal konnte nicht geöffnet werden',
    load_failed_body: 'Die Verbindung ist fehlgeschlagen. Nichts ist verloren.',
    followup_kicker: 'Eine Woche später',
    followup_label: 'Ihre Antwort, in einem Satz',
    followup_placeholder: 'Ein Satz genügt.',
    sending: 'Wird gesendet…',
    reply: 'Antworten',
    empty_title: 'Heute gibt es nichts zu erzählen',
    empty_body: 'Das Journal öffnet sich am Tag nach einer Szene. Kommen Sie morgen wieder.',
    skipped_title: 'Eintrag übersprungen',
    skipped_body: 'Diese Szene wird nicht mehr angeboten. Die nächste kommt morgen.',
    headline: 'Das Logbuch',
    cue_fallback: 'Die Szene von gestern',
    field_label: 'Gestern, auf Französisch',
    hint: 'Eine Korrektur vorab, die ganze Liste auf Wunsch. In einer Woche fragt eine Zeile Sie noch einmal nach dieser Szene.',
    word_count: '{n} Wort/Wörter · mindestens {min}',
    correcting: 'Wird korrigiert…',
    send: 'Senden',
    foot_note: 'Die Szene nach dem Senden nachlesen',
    skip: 'Diese Szene überspringen',
    entry_fallback: 'Ihr Eintrag',
    french_label: 'Ihr Französisch',
    hide_detail: 'Details ausblenden',
    show_all: 'Alle ansehen',
    errata_one: 'Ein Fehler ist im Relevé notiert und kommt in einer Szene wieder.',
    errata_many: '{n} Fehler sind im Relevé notiert und kommen in einer Szene wieder.',
    recall_label: 'Woran Sie sich erinnern',
    recall_empty: 'Hier gibt es nichts zu prüfen.',
    reveal_label: 'Die Szene, wie sie war',
  },
  legacy: {
    course: 'Kurs · {level}',
    progress_unavailable: 'Fortschritt nicht verfügbar',
    settings: 'Einstellungen',
    tab_grammar: 'Grammatik',
    tab_vocabulary: 'Wortschatz',
    modes_label: 'Bereiche des Hefts',
    resume: 'Fortsetzen →',
    filters: 'Filter',
    due: 'Zu wiederholen',
    due_suffix: ', zu wiederholen',
    state_new: 'Neu',
    errata: '{n} Fehler',
    mastery: 'Beherrschung {n} von 10',
    notice_label: 'Hinweis aus dem Archiv',
    map_legend: 'Verteilung nach Stand',
    empty_title: 'Keine Karte in dieser Ansicht',
    colophon: 'Les Cahiers · Referenzausgabe',
  },
  biography: {
    no_date: 'Ohne Datum',
    source_anki_deck: 'Importiertes Deck',
    source_deck: 'Deck',
    source_errata: 'Fehler',
    source_review: 'Wiederholung',
    source_pilot_capture: 'Pilot-Erfassung',
    examples: 'Beispiele',
    title_fallback: 'Der Faden des Worts',
    eyebrow: 'Die Geschichte des Worts',
    opening: 'Wird geöffnet…',
    loading: 'Die Geschichte wird geöffnet…',
    failed: 'Die Geschichte ist nicht verfügbar.',
    ledger_label: 'Stand des Gedächtnisses',
    tile_state: 'Stand',
    tile_seen: 'Gesehen',
    tile_used: 'Verwendet',
    tile_errata: 'Fehler',
    thread: 'Der Faden',
    no_trace: 'Dieses Wort hat noch keine Spur hinterlassen.',
  },
  fragility: {
    new: 'Neu',
    new_reason_unseen: 'Von Ihnen noch nicht wiederholt.',
    new_reason: 'Noch nicht wiederholt.',
    due: 'Zu wiederholen',
    due_reason: 'Bereit für eine Wiederholung.',
    fraying: 'Erinnerung schwindet',
    fraying_reason: 'Mehrmals vergessen oder geringe geschätzte Erinnerung.',
    tender: 'Brüchige Erinnerung',
    tender_reason: 'Nützlich, aber noch leicht zu verlieren.',
    holding: 'Sitzt',
    holding_reason: 'Dieser Faden hält vorerst gut.',
    forming: 'Im Aufbau',
    forming_reason: 'Der Faden nimmt Gestalt an.',
  },
};

const TABLES: Record<ControlLanguage, CahierCopy> = { en: EN, de: DE, fr: FR };

/** The Cahier copy table for a chrome language (regional tags and nulls normalised). */
export function cahierCopy(language: unknown): CahierCopy {
  return TABLES[normalizeControlLanguage(language)];
}

/** The copy table of the surrounding `AtelierV2Root` (its `language` prop). */
export function useCahierCopy(): CahierCopy {
  return cahierCopy(useControlLanguage());
}

/** `{n}`-style placeholders filled in. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in values ? String(values[key]) : match));
}

/** «3 fiches», «1 fiche»: the `_one` / `_many` pair of a group, with `{n}` filled. */
export function countLabel<G extends Record<string, string>>(
  group: G,
  stem: string,
  n: number,
): string {
  const key = `${stem}_${n === 1 ? 'one' : 'many'}`;
  const template = group[key];
  return typeof template === 'string' ? fill(template, { n }) : String(n);
}
