/**
 * WP-82 — Le Courrier follows the one language rule.
 *
 * The Courrier's own words — the status lines, the buttons, the composer's
 * labels, the notices, the verdict on the seal, the loading and empty states,
 * the aria-labels — are chrome: up to A2 they are the learner's language, from
 * B1 they are French (`chromeLanguage`, `lib/language-rule.ts`). The letter
 * itself (the correspondent's lines, the situation, the words to place, the
 * correspondent's name, the mood line the server wrote) is content and stays
 * French whatever this table says. Place names — Le Courrier, Le Feuilleton,
 * La Une, L’Atelier — are French in every column.
 *
 * The French column is the publication voice it always was, trimmed to the
 * text diet. `{name}`-style placeholders are filled with `crFill`.
 */

import type { ControlLanguage } from '@/types/daily-journey';

import { useControlLanguage } from '@/components/atelier-v2/ui/AtelierV2Root';
import { normalizeControlLanguage } from '@/lib/atelier-v2-copy';

const FR = {
  lang: 'fr',
  locale: 'fr-FR',
  // places (French in every column)
  courrier: 'Le Courrier',
  feuilleton: 'Le Feuilleton',
  feuilleton_act: 'Le Feuilleton · Acte {n}',
  // page
  documents_title: 'Vos documents',
  page_aria_intake: 'Le Courrier · vos documents',
  page_aria_act: 'Le Feuilleton · acte',
  back_home: 'Retour à la Une',
  back_atelier: 'Retour à l’Atelier',
  loading_courrier: 'Chargement du courrier',
  loading_documents: 'Chargement de vos documents',
  error_title: 'Courrier égaré',
  error_open: 'Ce courrier n’a pas pu être ouvert.',
  error_not_ready: 'L’acte suivant n’est pas encore ouvert : lisez d’abord l’épisode en cours du Feuilleton.',
  retry: 'Réessayer',
  empty_title: 'Aucun courrier pour l’instant.',
  empty_body: 'Le facteur repassera demain.',
  // translate
  translate: 'Traduire',
  translate_hide: 'Masquer',
  translate_show_aria: 'Voir la traduction',
  translate_hide_aria: 'Masquer la traduction',
  translate_loading: 'Traduction…',
  translate_unavailable: 'Traduction indisponible.',
  // header + status
  cadence_weekly: 'Courrier de la semaine',
  cadence_post_session: 'Après la séance',
  status_done: 'Bouclé · {date}',
  status_lapsed: 'Sans réponse',
  status_in_progress: 'En cours',
  status_email: 'Reçu · à rédiger',
  status_form: 'Dossier · à déposer',
  status_voicemail: 'Message reçu · à rappeler',
  status_call: 'Appel · ligne ouverte',
  status_received: 'Reçu ce matin',
  chip_done: 'Bouclé',
  chip_placed_sr: 'mots placés',
  archive_k: 'Courrier passé',
  archive_done: 'Bouclé',
  archive_in_progress: 'En cours',
  archive_todo: 'À traiter',
  // the letter's furniture
  situation_aria: 'La situation',
  todo: 'À faire ·',
  ribbon_aria: 'Mots à placer',
  ribbon_k: 'À placer',
  ribbon_used_sr: 'placé',
  you: 'Vous',
  repair_aria: 'Correction',
  repair_one: 'Bien dit · une petite remarque',
  repair_many: 'Bien dit · {n} petites remarques',
  repairs_saved_one: '{n} réparation enregistrée',
  repairs_saved_many: '{n} réparations enregistrées',
  memo_head: 'Message téléphonique',
  memo_transcript_sr: 'Transcription automatique',
  memo_from: 'De la part de',
  memo_channel: 'Canal',
  memo_answered: 'Répondu',
  unassessed: 'Pas encore corrigé : le correcteur n’était pas disponible.',
  typing: '{name} rédige sa réponse',
  // composer
  reply: 'Répondre',
  reply_to: 'Répondre à {name}',
  quick_aria: 'Réponses rapides',
  send: 'Envoyer',
  send_email: 'Envoyer l’email',
  send_form: 'Déposer',
  finish: 'Terminer',
  finishing: 'Clôture…',
  finish_gate: 'Envoyez d’abord une réponse.',
  composer_label_chat: 'Votre réponse',
  composer_placeholder_chat: 'Votre réponse en français…',
  composer_label_email: 'Votre email',
  composer_instruction_email: 'Un objet, une formule d’appel, le corps, une formule de politesse.',
  composer_label_form: 'Le formulaire',
  composer_instruction_form: 'Remplissez les champs, en phrases complètes là où c’est demandé.',
  composer_label_voicemail: 'Votre message vocal',
  composer_instruction_voicemail: 'Répondez à l’oral, ou écrivez.',
  composer_label_call: 'Au téléphone',
  composer_instruction_call: 'Une réponse courte, à l’oral ou par écrit.',
  composer_placeholder_voice: 'Parlez, ou écrivez ici…',
  composer_label_last: 'Dernière réponse',
  composer_instruction_last: 'C’est compris. Confirmez le dernier détail ou terminez.',
  composer_placeholder_last: 'Confirmez brièvement en français…',
  composer_label_reply: 'Votre réponse',
  composer_instruction_quoted: 'Dernier message : « {text} » Répondez-y.',
  composer_instruction_reply: 'Répondez au dernier message.',
  composer_placeholder_reply: 'Répondez au dernier message…',
  // the mic
  mic_start: 'Enregistrer une réponse vocale',
  mic_stop: 'Arrêter l’enregistrement',
  mic_recording: 'Enregistrement · {timer}',
  // toasts
  toast_send_failed: 'Le message n’est pas parti.',
  toast_act_done: 'Acte bouclé',
  toast_courrier_done: 'Courrier bouclé',
  toast_finish_failed: 'Ce courrier n’a pas pu être terminé.',
  toast_new_act: 'Nouvel acte ouvert',
  toast_new_courrier: 'Nouveau courrier ouvert',
  toast_new_failed: 'Le nouveau courrier n’a pas pu être créé.',
  // the seal (answered letter)
  resolved_aria: 'Lettre bouclée',
  seal_resolved: 'Résolu',
  seal_act_done: 'Acte bouclé',
  seal_numbers_aria: 'En chiffres',
  // the correspondent's face on the seal — phrasings that need no gender
  seal_mood_happy: '{name} vous sourit',
  seal_mood_neutral: '{name} reste neutre',
  seal_mood_distant: '{name} garde ses distances',
  seal_mood_cross: '{name} vous en veut',
  token_minted: 'Jeton frappé',
  next_act: 'Lire l’acte suivant',
  new_courrier: 'Nouveau courrier',
  num_objectives: 'objectifs tenus',
  num_repairs_one: 'réparation',
  num_repairs_many: 'réparations',
  num_words_one: 'mot écrit',
  num_words_many: 'mots écrits',
  num_saved_one: 'phrase gardée',
  num_saved_many: 'phrases gardées',
  num_replies_one: 'réponse',
  num_replies_many: 'réponses',
  num_errors_one: 'erreur repérée',
  num_errors_many: 'erreurs repérées',
  // outcomes
  outcome_kept: 'Parole tenue',
  outcome_partial: 'En partie',
  outcome_missed: 'Manqué cette fois',
  outcome_ignored: 'Restée sans réponse',
  sentence_kept_named: 'Vous avez fait ce que {name} demandait.',
  sentence_kept: 'Vous avez fait ce que la lettre demandait.',
  sentence_partial: 'Une partie de ce qu’on vous demandait est passée ; le reste attend.',
  sentence_missed: 'Ce qu’on vous demandait n’est pas passé cette fois.',
  sentence_ignored: 'La lettre est restée sans réponse.',
  // the correspondence
  chain_label: '{ord} lettre sur {total}',
  chain_from: '{chain}, de {name}',
  expiry_today: 'Répondez aujourd’hui, si vous pouvez.',
  expiry_tomorrow: 'Répondez d’ici demain, si vous pouvez.',
  expiry_weekday: 'Répondez avant {day}, si vous pouvez.',
  expiry_date: 'Répondez avant le {date}, si vous pouvez.',
  corr_aria: 'Votre correspondance avec {name}',
  corr_prev_one: 'Votre lettre précédente',
  corr_prev_many: 'Vos {n} lettres précédentes',
  letter_fallback: 'Une lettre du Courrier.',
  lapsed_aria: 'Lettre sans réponse',
  lapsed_named: 'Le délai est passé et {name} n’a rien reçu. Ce n’est pas grave : {name} en dira un mot dans sa prochaine lettre.',
  lapsed_anon: 'Le délai est passé. Ce n’est pas grave : votre correspondant en dira un mot dans sa prochaine lettre.',
  measured_objectives: 'Objectifs tenus',
  measured_objectives_value: '{met} sur {total}',
  measured_unassessed: 'pas encore corrigés',
  measured_repairs: 'Réparations',
  measured_repairs_one: '{n} enregistrée',
  measured_repairs_many: '{n} enregistrées',
  measured_saved: 'Phrases mises de côté',
  measured_words: 'Mots écrits',
  debrief_aria: 'Ce que cette lettre a donné',
  debrief_keeps_named: 'Ce que {name} retient',
  debrief_keeps_anon: 'Ce que votre correspondant retient',
  debrief_since: 'Depuis votre lettre — ',
  debrief_on_receipt: 'À la réception de votre lettre — ',
  // the waiting-letter row (La Une, the Feuilleton)
  letter_waiting: 'Une lettre vous attend',
  reply_started: 'Votre réponse est commencée',
  hint_waiting_named: '{name} attend votre réponse',
  hint_story_named: '{name} vous écrit après l’épisode',
  hint_story_anon: 'Quelqu’un vous écrit après l’épisode',
  hint_default: 'Le Courrier vous attend.',
  read_and_reply: 'Lire et répondre',
  read_and_reply_min: 'Lire et répondre · {n} min',
  envelope: 'Une lettre scellée',
  envelope_named: 'Une lettre scellée, de {name}',
  // «Apportez votre français»
  intake_link: 'Apportez votre français',
  intake_link_hint: 'Une lettre, un menu, un courriel : on le lit avec vous.',
  cap_off: 'La lecture de vos documents est désactivée pour l’instant.',
  cap_none: 'Vous avez fait lire tous vos documents de la semaine.',
  cap_one: 'Il vous reste un document cette semaine.',
  cap_many: 'Il vous reste {n} documents cette semaine.',
  intake_kicker: 'Le Courrier · Vos documents',
  intake_head: 'Un menu, une lettre : on le lit avec vous.',
  intake_paste: 'Coller un texte',
  intake_photo: 'Photographier',
  intake_photo_change: 'Changer la photo',
  intake_privacy: 'privés, supprimables, jamais dans le feuilleton.',
  intake_paste_label: 'Collez le texte de votre document',
  intake_paste_placeholder: 'Collez votre document ici…',
  intake_remove: 'Retirer',
  intake_close: 'Fermer',
  intake_reading: 'Lecture…',
  intake_read: 'Faire lire',
  intake_empty: 'Rien encore. Votre premier document arrivera ici, résumé à votre niveau.',
  intake_error: 'Ce document n’a pas pu être lu. Réessayez dans un instant.',
  art_aria: 'Votre document',
  art_untitled: 'Votre document',
  art_a_document: 'Un document',
  art_photographed: 'photographié',
  art_received: 'reçue le {date}',
  art_bounded: '(résumé abrégé)',
  art_words_k: 'Les mots que vous ne connaissiez pas',
  art_no_gloss: 'traduction indisponible',
  art_off_lexicon: 'hors lexique',
  art_queued_one: 'Ce mot rejoint votre lexique.',
  art_queued_many: 'Ces {n} mots rejoignent votre lexique.',
  art_deleting: 'Suppression…',
  art_delete: 'Supprimer ce document et sa tâche',
  task_aria: 'Votre tâche',
  task_opening: 'Ouverture…',
  task_kind_reply: 'Répondre',
  task_kind_decide: 'Choisir',
  task_kind_ask: 'Demander',
  unread_aria: 'Document non lu',
  unread: 'Non lu',
  unread_photo: 'Ce document n’a pas pu être lu. Reprenez la photo de plus près, bien à plat, puis réessayez.',
  unread_delete: 'Supprimer',
};

export type CourrierCopy = Record<keyof typeof FR, string>;

const EN: CourrierCopy = {
  lang: 'en',
  locale: 'en-GB',
  courrier: 'Le Courrier',
  feuilleton: 'Le Feuilleton',
  feuilleton_act: 'Le Feuilleton · Act {n}',
  documents_title: 'Your documents',
  page_aria_intake: 'Le Courrier · your documents',
  page_aria_act: 'Le Feuilleton · act',
  back_home: 'Back to La Une',
  back_atelier: 'Back to L’Atelier',
  loading_courrier: 'Loading your letter',
  loading_documents: 'Loading your documents',
  error_title: 'This letter went missing',
  error_open: 'This letter could not be opened.',
  error_not_ready: 'The next act is not open yet: read the current Feuilleton episode first.',
  retry: 'Try again',
  empty_title: 'No letter for now.',
  empty_body: 'The postman comes back tomorrow.',
  translate: 'Translate',
  translate_hide: 'Hide',
  translate_show_aria: 'Show the translation',
  translate_hide_aria: 'Hide the translation',
  translate_loading: 'Translating…',
  translate_unavailable: 'Translation unavailable.',
  cadence_weekly: 'This week’s letter',
  cadence_post_session: 'After the session',
  status_done: 'Done · {date}',
  status_lapsed: 'Unanswered',
  status_in_progress: 'In progress',
  status_email: 'Received · to write',
  status_form: 'Form · to file',
  status_voicemail: 'Voicemail · to call back',
  status_call: 'Call · line open',
  status_received: 'Arrived this morning',
  chip_done: 'Done',
  chip_placed_sr: 'words used',
  archive_k: 'Past letters',
  archive_done: 'Done',
  archive_in_progress: 'In progress',
  archive_todo: 'To answer',
  situation_aria: 'The situation',
  todo: 'To do ·',
  ribbon_aria: 'Words to use',
  ribbon_k: 'Use',
  ribbon_used_sr: 'used',
  you: 'You',
  repair_aria: 'Correction',
  repair_one: 'Well said · one small note',
  repair_many: 'Well said · {n} small notes',
  repairs_saved_one: '{n} fix saved',
  repairs_saved_many: '{n} fixes saved',
  memo_head: 'Phone message',
  memo_transcript_sr: 'Automatic transcript',
  memo_from: 'From',
  memo_channel: 'Channel',
  memo_answered: 'Answered',
  unassessed: 'Not corrected yet: the corrector was unavailable.',
  typing: '{name} is writing back',
  reply: 'Reply',
  reply_to: 'Reply to {name}',
  quick_aria: 'Quick replies',
  send: 'Send',
  send_email: 'Send the email',
  send_form: 'Submit',
  finish: 'Finish',
  finishing: 'Finishing…',
  finish_gate: 'Send a reply first.',
  composer_label_chat: 'Your reply',
  composer_placeholder_chat: 'Your reply, in French…',
  composer_label_email: 'Your email',
  composer_instruction_email: 'A subject, a greeting, the body, a closing line.',
  composer_label_form: 'The form',
  composer_instruction_form: 'Fill in the fields, in full sentences where asked.',
  composer_label_voicemail: 'Your voice message',
  composer_instruction_voicemail: 'Answer out loud, or type.',
  composer_label_call: 'On the phone',
  composer_instruction_call: 'A short answer, spoken or typed.',
  composer_placeholder_voice: 'Speak, or type here…',
  composer_label_last: 'Last reply',
  composer_instruction_last: 'Understood. Confirm the last detail or finish.',
  composer_placeholder_last: 'Confirm briefly, in French…',
  composer_label_reply: 'Your reply',
  composer_instruction_quoted: 'Last message: “{text}” Answer it.',
  composer_instruction_reply: 'Answer the last message.',
  composer_placeholder_reply: 'Answer the last message…',
  mic_start: 'Record a voice reply',
  mic_stop: 'Stop recording',
  mic_recording: 'Recording · {timer}',
  toast_send_failed: 'Your message was not sent.',
  toast_act_done: 'Act complete',
  toast_courrier_done: 'Letter answered',
  toast_finish_failed: 'This letter could not be finished.',
  toast_new_act: 'New act opened',
  toast_new_courrier: 'New letter opened',
  toast_new_failed: 'The new letter could not be created.',
  resolved_aria: 'Letter answered',
  seal_resolved: 'Answered',
  seal_act_done: 'Act complete',
  seal_numbers_aria: 'In numbers',
  seal_mood_happy: '{name} is pleased with you',
  seal_mood_neutral: '{name} is neutral',
  seal_mood_distant: '{name} is a little distant',
  seal_mood_cross: '{name} is cross with you',
  token_minted: 'Token minted',
  next_act: 'Read the next act',
  new_courrier: 'New letter',
  num_objectives: 'goals met',
  num_repairs_one: 'fix',
  num_repairs_many: 'fixes',
  num_words_one: 'word written',
  num_words_many: 'words written',
  num_saved_one: 'phrase kept',
  num_saved_many: 'phrases kept',
  num_replies_one: 'reply',
  num_replies_many: 'replies',
  num_errors_one: 'error spotted',
  num_errors_many: 'errors spotted',
  outcome_kept: 'Promise kept',
  outcome_partial: 'Partly',
  outcome_missed: 'Missed this time',
  outcome_ignored: 'Left unanswered',
  sentence_kept_named: 'You did what {name} asked.',
  sentence_kept: 'You did what the letter asked.',
  sentence_partial: 'Part of what was asked got through; the rest can wait.',
  sentence_missed: 'What was asked did not get through this time.',
  sentence_ignored: 'The letter was left unanswered.',
  chain_label: 'Letter {n} of {total}',
  chain_from: '{chain}, from {name}',
  expiry_today: 'Reply today if you can.',
  expiry_tomorrow: 'Reply by tomorrow if you can.',
  expiry_weekday: 'Reply by {day} if you can.',
  expiry_date: 'Reply by {date} if you can.',
  corr_aria: 'Your letters with {name}',
  corr_prev_one: 'Your previous letter',
  corr_prev_many: 'Your {n} previous letters',
  letter_fallback: 'A letter from Le Courrier.',
  lapsed_aria: 'Unanswered letter',
  lapsed_named: 'The time ran out and {name} got nothing. It is fine: {name} will mention it in the next letter.',
  lapsed_anon: 'The time ran out. It is fine: your correspondent will mention it in the next letter.',
  measured_objectives: 'Goals met',
  measured_objectives_value: '{met} of {total}',
  measured_unassessed: 'not corrected yet',
  measured_repairs: 'Fixes',
  measured_repairs_one: '{n} saved',
  measured_repairs_many: '{n} saved',
  measured_saved: 'Phrases kept',
  measured_words: 'Words written',
  debrief_aria: 'What this letter did',
  debrief_keeps_named: 'What {name} remembers',
  debrief_keeps_anon: 'What your correspondent remembers',
  debrief_since: 'Since your letter — ',
  debrief_on_receipt: 'When your letter arrived — ',
  letter_waiting: 'A letter is waiting',
  reply_started: 'You started your reply',
  hint_waiting_named: '{name} is waiting for your reply',
  hint_story_named: '{name} writes to you after the episode',
  hint_story_anon: 'Someone writes to you after the episode',
  hint_default: 'Le Courrier is waiting for you.',
  read_and_reply: 'Read and reply',
  read_and_reply_min: 'Read and reply · {n} min',
  envelope: 'A sealed letter',
  envelope_named: 'A sealed letter from {name}',
  intake_link: 'Bring your own French',
  intake_link_hint: 'A letter, a menu, an email: we read it with you.',
  cap_off: 'Reading your documents is switched off for now.',
  cap_none: 'You have used all of this week’s documents.',
  cap_one: 'You have one document left this week.',
  cap_many: 'You have {n} documents left this week.',
  intake_kicker: 'Le Courrier · Your documents',
  intake_head: 'A menu, a letter: we read it with you.',
  intake_paste: 'Paste a text',
  intake_photo: 'Take a photo',
  intake_photo_change: 'Change the photo',
  intake_privacy: 'private, deletable, never in the feuilleton.',
  intake_paste_label: 'Paste the text of your document',
  intake_paste_placeholder: 'Paste your document here…',
  intake_remove: 'Remove',
  intake_close: 'Close',
  intake_reading: 'Reading…',
  intake_read: 'Read it',
  intake_empty: 'Nothing yet. Your first document will arrive here, summed up at your level.',
  intake_error: 'This document could not be read. Try again in a moment.',
  art_aria: 'Your document',
  art_untitled: 'Your document',
  art_a_document: 'A document',
  art_photographed: 'photographed',
  art_received: 'received {date}',
  art_bounded: '(shortened summary)',
  art_words_k: 'The words you did not know',
  art_no_gloss: 'no translation',
  art_off_lexicon: 'not in your lexique',
  art_queued_one: 'This word joins your lexique.',
  art_queued_many: 'These {n} words join your lexique.',
  art_deleting: 'Deleting…',
  art_delete: 'Delete this document and its task',
  task_aria: 'Your task',
  task_opening: 'Opening…',
  task_kind_reply: 'Reply',
  task_kind_decide: 'Choose',
  task_kind_ask: 'Ask',
  unread_aria: 'Document not read',
  unread: 'Not read',
  unread_photo: 'This document could not be read. Take the photo closer, flat, then try again.',
  unread_delete: 'Delete',
};

const DE: CourrierCopy = {
  lang: 'de',
  locale: 'de-DE',
  courrier: 'Le Courrier',
  feuilleton: 'Le Feuilleton',
  feuilleton_act: 'Le Feuilleton · Akt {n}',
  documents_title: 'Deine Dokumente',
  page_aria_intake: 'Le Courrier · deine Dokumente',
  page_aria_act: 'Le Feuilleton · Akt',
  back_home: 'Zurück zu La Une',
  back_atelier: 'Zurück zu L’Atelier',
  loading_courrier: 'Dein Brief wird geladen',
  loading_documents: 'Deine Dokumente werden geladen',
  error_title: 'Dieser Brief ist verloren gegangen',
  error_open: 'Dieser Brief ließ sich nicht öffnen.',
  error_not_ready: 'Der nächste Akt ist noch nicht offen: Lies zuerst die aktuelle Feuilleton-Episode.',
  retry: 'Nochmal versuchen',
  empty_title: 'Gerade kein Brief.',
  empty_body: 'Der Briefträger kommt morgen wieder.',
  translate: 'Übersetzen',
  translate_hide: 'Ausblenden',
  translate_show_aria: 'Übersetzung zeigen',
  translate_hide_aria: 'Übersetzung ausblenden',
  translate_loading: 'Wird übersetzt…',
  translate_unavailable: 'Keine Übersetzung verfügbar.',
  cadence_weekly: 'Brief der Woche',
  cadence_post_session: 'Nach der Sitzung',
  status_done: 'Erledigt · {date}',
  status_lapsed: 'Unbeantwortet',
  status_in_progress: 'Angefangen',
  status_email: 'Erhalten · zu schreiben',
  status_form: 'Formular · abzugeben',
  status_voicemail: 'Sprachnachricht · zurückrufen',
  status_call: 'Anruf · Leitung offen',
  status_received: 'Heute Morgen angekommen',
  chip_done: 'Erledigt',
  chip_placed_sr: 'Wörter verwendet',
  archive_k: 'Frühere Briefe',
  archive_done: 'Erledigt',
  archive_in_progress: 'Angefangen',
  archive_todo: 'Offen',
  situation_aria: 'Die Situation',
  todo: 'Zu tun ·',
  ribbon_aria: 'Wörter zum Verwenden',
  ribbon_k: 'Verwende',
  ribbon_used_sr: 'verwendet',
  you: 'Du',
  repair_aria: 'Korrektur',
  repair_one: 'Gut gesagt · ein kleiner Hinweis',
  repair_many: 'Gut gesagt · {n} kleine Hinweise',
  repairs_saved_one: '{n} Korrektur gespeichert',
  repairs_saved_many: '{n} Korrekturen gespeichert',
  memo_head: 'Telefonnachricht',
  memo_transcript_sr: 'Automatisches Transkript',
  memo_from: 'Von',
  memo_channel: 'Kanal',
  memo_answered: 'Beantwortet',
  unassessed: 'Noch nicht korrigiert: Die Korrektur war nicht verfügbar.',
  typing: '{name} schreibt zurück',
  reply: 'Antworten',
  reply_to: 'Antworten an {name}',
  quick_aria: 'Schnelle Antworten',
  send: 'Senden',
  send_email: 'E-Mail senden',
  send_form: 'Abgeben',
  finish: 'Beenden',
  finishing: 'Wird beendet…',
  finish_gate: 'Sende zuerst eine Antwort.',
  composer_label_chat: 'Deine Antwort',
  composer_placeholder_chat: 'Deine Antwort auf Französisch…',
  composer_label_email: 'Deine E-Mail',
  composer_instruction_email: 'Ein Betreff, eine Anrede, der Text, ein Gruß.',
  composer_label_form: 'Das Formular',
  composer_instruction_form: 'Fülle die Felder aus, in ganzen Sätzen, wo verlangt.',
  composer_label_voicemail: 'Deine Sprachnachricht',
  composer_instruction_voicemail: 'Antworte laut, oder schreibe.',
  composer_label_call: 'Am Telefon',
  composer_instruction_call: 'Eine kurze Antwort, gesprochen oder geschrieben.',
  composer_placeholder_voice: 'Sprich, oder schreibe hier…',
  composer_label_last: 'Letzte Antwort',
  composer_instruction_last: 'Verstanden. Bestätige das letzte Detail oder beende.',
  composer_placeholder_last: 'Kurz auf Französisch bestätigen…',
  composer_label_reply: 'Deine Antwort',
  composer_instruction_quoted: 'Letzte Nachricht: „{text}“ Antworte darauf.',
  composer_instruction_reply: 'Antworte auf die letzte Nachricht.',
  composer_placeholder_reply: 'Antworte auf die letzte Nachricht…',
  mic_start: 'Sprachantwort aufnehmen',
  mic_stop: 'Aufnahme beenden',
  mic_recording: 'Aufnahme · {timer}',
  toast_send_failed: 'Deine Nachricht wurde nicht gesendet.',
  toast_act_done: 'Akt abgeschlossen',
  toast_courrier_done: 'Brief beantwortet',
  toast_finish_failed: 'Dieser Brief ließ sich nicht beenden.',
  toast_new_act: 'Neuer Akt geöffnet',
  toast_new_courrier: 'Neuer Brief geöffnet',
  toast_new_failed: 'Der neue Brief ließ sich nicht erstellen.',
  resolved_aria: 'Brief beantwortet',
  seal_resolved: 'Beantwortet',
  seal_act_done: 'Akt abgeschlossen',
  seal_numbers_aria: 'In Zahlen',
  seal_mood_happy: '{name} ist zufrieden mit Ihnen',
  seal_mood_neutral: '{name} ist neutral',
  seal_mood_distant: '{name} ist etwas distanziert',
  seal_mood_cross: '{name} ist verärgert',
  token_minted: 'Marke geprägt',
  next_act: 'Nächsten Akt lesen',
  new_courrier: 'Neuer Brief',
  num_objectives: 'Ziele erreicht',
  num_repairs_one: 'Korrektur',
  num_repairs_many: 'Korrekturen',
  num_words_one: 'Wort geschrieben',
  num_words_many: 'Wörter geschrieben',
  num_saved_one: 'Satz behalten',
  num_saved_many: 'Sätze behalten',
  num_replies_one: 'Antwort',
  num_replies_many: 'Antworten',
  num_errors_one: 'Fehler gefunden',
  num_errors_many: 'Fehler gefunden',
  outcome_kept: 'Wort gehalten',
  outcome_partial: 'Teilweise',
  outcome_missed: 'Diesmal verpasst',
  outcome_ignored: 'Unbeantwortet geblieben',
  sentence_kept_named: 'Du hast getan, worum {name} gebeten hat.',
  sentence_kept: 'Du hast getan, worum der Brief gebeten hat.',
  sentence_partial: 'Ein Teil ist angekommen; der Rest kann warten.',
  sentence_missed: 'Worum gebeten wurde, ist diesmal nicht angekommen.',
  sentence_ignored: 'Der Brief ist unbeantwortet geblieben.',
  chain_label: 'Brief {n} von {total}',
  chain_from: '{chain}, von {name}',
  expiry_today: 'Antworte heute, wenn du kannst.',
  expiry_tomorrow: 'Antworte bis morgen, wenn du kannst.',
  expiry_weekday: 'Antworte bis {day}, wenn du kannst.',
  expiry_date: 'Antworte bis zum {date}, wenn du kannst.',
  corr_aria: 'Deine Briefe mit {name}',
  corr_prev_one: 'Dein vorheriger Brief',
  corr_prev_many: 'Deine {n} vorherigen Briefe',
  letter_fallback: 'Ein Brief aus Le Courrier.',
  lapsed_aria: 'Unbeantworteter Brief',
  lapsed_named: 'Die Zeit ist abgelaufen und {name} hat nichts bekommen. Nicht schlimm: {name} erwähnt es im nächsten Brief.',
  lapsed_anon: 'Die Zeit ist abgelaufen. Nicht schlimm: Dein Briefpartner erwähnt es im nächsten Brief.',
  measured_objectives: 'Ziele erreicht',
  measured_objectives_value: '{met} von {total}',
  measured_unassessed: 'noch nicht korrigiert',
  measured_repairs: 'Korrekturen',
  measured_repairs_one: '{n} gespeichert',
  measured_repairs_many: '{n} gespeichert',
  measured_saved: 'Behaltene Sätze',
  measured_words: 'Geschriebene Wörter',
  debrief_aria: 'Was dieser Brief bewirkt hat',
  debrief_keeps_named: 'Was {name} behält',
  debrief_keeps_anon: 'Was dein Briefpartner behält',
  debrief_since: 'Seit deinem Brief — ',
  debrief_on_receipt: 'Als dein Brief ankam — ',
  letter_waiting: 'Ein Brief wartet auf dich',
  reply_started: 'Du hast deine Antwort angefangen',
  hint_waiting_named: '{name} wartet auf deine Antwort',
  hint_story_named: '{name} schreibt dir nach der Episode',
  hint_story_anon: 'Jemand schreibt dir nach der Episode',
  hint_default: 'Le Courrier wartet auf dich.',
  read_and_reply: 'Lesen und antworten',
  read_and_reply_min: 'Lesen und antworten · {n} Min.',
  envelope: 'Ein versiegelter Brief',
  envelope_named: 'Ein versiegelter Brief von {name}',
  intake_link: 'Bring dein eigenes Französisch',
  intake_link_hint: 'Ein Brief, eine Speisekarte, eine E-Mail: Wir lesen es mit dir.',
  cap_off: 'Das Lesen deiner Dokumente ist gerade ausgeschaltet.',
  cap_none: 'Du hast alle Dokumente dieser Woche lesen lassen.',
  cap_one: 'Du hast diese Woche noch ein Dokument.',
  cap_many: 'Du hast diese Woche noch {n} Dokumente.',
  intake_kicker: 'Le Courrier · Deine Dokumente',
  intake_head: 'Eine Speisekarte, ein Brief: Wir lesen es mit dir.',
  intake_paste: 'Text einfügen',
  intake_photo: 'Fotografieren',
  intake_photo_change: 'Foto ändern',
  intake_privacy: 'privat, löschbar, nie im Feuilleton.',
  intake_paste_label: 'Füge den Text deines Dokuments ein',
  intake_paste_placeholder: 'Füge dein Dokument hier ein…',
  intake_remove: 'Entfernen',
  intake_close: 'Schließen',
  intake_reading: 'Wird gelesen…',
  intake_read: 'Lesen lassen',
  intake_empty: 'Noch nichts. Dein erstes Dokument erscheint hier, auf deinem Niveau zusammengefasst.',
  intake_error: 'Dieses Dokument ließ sich nicht lesen. Versuche es gleich noch einmal.',
  art_aria: 'Dein Dokument',
  art_untitled: 'Dein Dokument',
  art_a_document: 'Ein Dokument',
  art_photographed: 'fotografiert',
  art_received: 'erhalten am {date}',
  art_bounded: '(gekürzte Zusammenfassung)',
  art_words_k: 'Die Wörter, die du nicht kanntest',
  art_no_gloss: 'keine Übersetzung',
  art_off_lexicon: 'nicht in deinem Lexique',
  art_queued_one: 'Dieses Wort kommt in dein Lexique.',
  art_queued_many: 'Diese {n} Wörter kommen in dein Lexique.',
  art_deleting: 'Wird gelöscht…',
  art_delete: 'Dieses Dokument und seine Aufgabe löschen',
  task_aria: 'Deine Aufgabe',
  task_opening: 'Wird geöffnet…',
  task_kind_reply: 'Antworten',
  task_kind_decide: 'Auswählen',
  task_kind_ask: 'Nachfragen',
  unread_aria: 'Dokument nicht gelesen',
  unread: 'Nicht gelesen',
  unread_photo: 'Dieses Dokument ließ sich nicht lesen. Fotografiere es näher und flach, dann versuche es noch einmal.',
  unread_delete: 'Löschen',
};

const TABLES: Record<ControlLanguage, CourrierCopy> = { en: EN, de: DE, fr: FR };

/** The Courrier's chrome in the language `chromeLanguage()` resolved. */
export function courrierCopy(language: unknown): CourrierCopy {
  return TABLES[normalizeControlLanguage(language)];
}

/** The Courrier's chrome for the language the surrounding `AtelierV2Root`
 *  was given — the page sets it from `useChromeLanguage()`. */
export function useCrCopy(): CourrierCopy {
  return courrierCopy(useControlLanguage());
}

/** `{name}`-style placeholders filled in; an unknown key is left as written. */
export function crFill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in values ? String(values[key]) : match));
}

/** One of a `_one` / `_many` pair, by count. */
export function crPlural(copy: CourrierCopy, stem: string, n: number): string {
  const key = `${stem}_${n === 1 ? 'one' : 'many'}` as keyof CourrierCopy;
  return crFill(copy[key], { n });
}

/**
 * A letter's headline in «previous letters» and on La Une. A real headline is
 * the letter's French; the server's fallback («Une lettre du Courrier.») is
 * chrome, so it is said in `language` — from the server's `{fr, en, de}` table
 * when it sent one, else from this table.
 */
export function crLetterHeadline(
  letter: { summary_fr?: unknown; summary_by_language?: unknown; title?: unknown } | null | undefined,
  language: unknown,
): { text: string; lang: string } {
  const t = courrierCopy(language);
  const french = String(letter?.summary_fr || letter?.title || '').trim();
  if (french && french !== FR.letter_fallback) return { text: french, lang: 'fr' };
  const table = letter?.summary_by_language;
  const served = table && typeof table === 'object' ? (table as Record<string, unknown>)[t.lang] : undefined;
  return {
    text: typeof served === 'string' && served.trim() ? served.trim() : t.letter_fallback,
    lang: t.lang,
  };
}

export default courrierCopy;
