"""Pydantic schemas package."""

from app.schemas.analytics import (
    AnalyticsStatisticsResponse,
    AnalyticsSummary,
    ErrorPattern,
    ErrorPatternsResponse,
    MetricPoint,
    StreakCalendarDay,
    StreakInfo,
    VocabularyHeatmapEntry,
    VocabularyHeatmapResponse,
)
from app.schemas.auth import Token, TokenPayload
from app.schemas.progress import (
    ProgressDetail,
    QueueWord,
    ReviewRequest,
    ReviewResponse,
)
from app.schemas.session import (
    AssistantTurnRead,
    DetectedErrorRead,
    ErrorFeedback,
    SessionCreateRequest,
    SessionMessageListResponse,
    SessionMessageRead,
    SessionMessageRequest,
    SessionOverview,
    SessionStartResponse,
    SessionStatusUpdate,
    SessionSummaryResponse,
    SessionTurnResponse,
    SessionTurnWordFeedback,
    TargetWordRead,
)
from app.schemas.user import UserBase, UserCreate, UserLogin, UserRead, UserUpdate
from app.schemas.vocabulary import VocabularyListResponse, VocabularyWordRead

__all__ = [
    "AnalyticsStatisticsResponse",
    "AnalyticsSummary",
    "Token",
    "TokenPayload",
    "ErrorPattern",
    "ErrorPatternsResponse",
    "MetricPoint",
    "StreakCalendarDay",
    "StreakInfo",
    "VocabularyHeatmapEntry",
    "VocabularyHeatmapResponse",
    "ProgressDetail",
    "QueueWord",
    "ReviewRequest",
    "ReviewResponse",
    "AssistantTurnRead",
    "DetectedErrorRead",
    "ErrorFeedback",
    "SessionCreateRequest",
    "SessionMessageListResponse",
    "SessionMessageRead",
    "SessionMessageRequest",
    "SessionOverview",
    "SessionStartResponse",
    "SessionStatusUpdate",
    "SessionSummaryResponse",
    "SessionTurnResponse",
    "SessionTurnWordFeedback",
    "TargetWordRead",
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserRead",
    "UserUpdate",
    "VocabularyListResponse",
    "VocabularyWordRead",
]
