version: "3.9"

services:
  api:
    image: ghcr.io/pechst1/conversational-language-learning:latest
    env_file:
      - ../.env.prod
    environment:
      RUN_MIGRATIONS: "1"
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      update_config:
        order: start-first
        parallelism: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: language_learning
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1000 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
