/**
 * WP-82 — the Feuilleton tab follows the one language rule.
 *
 * The pages around the reader — /graphic-novel, the season (/serial), an
 * episode read again from the archive (/serial/episode/[n]) and the cast
 * (/serial/cast) — print their own words from this table: the notices, the
 * buttons, the toasts, the loading and empty states, the aria-labels. Up to A2
 * they are the learner's language, from B1 French (`chromeLanguage`,
 * `lib/language-rule.ts`). The reader's own chrome lives in
 * `reader/reader-copy.ts`.
 *
 * What stays French whatever this table says: the story (a panel's lines, an
 * episode's title, a chapter's title, a character's callback, the season's
 * threads and promises), and the names of places and tabs — Le Feuilleton,
 * La saison, Les personnages, L’épisode, Le Courrier, La Une, L’Atelier.
 *
 * `{name}`-style placeholders are filled with `fbFill`.
 */

import type { ControlLanguage } from '@/types/daily-journey';

import { normalizeControlLanguage } from '@/lib/atelier-v2-copy';

const FR = {
  lang: 'fr',
  // places and tabs (French in every column)
  feuilleton: 'Le Feuilleton',
  // ---- /graphic-novel: toasts and state lines
  gen_failed: 'L’édition n’a pas pu être composée.',
  scene_unavailable: 'La planche de l’épisode n’a pas pu être ouverte. Relancez l’édition.',
  gen_stalled: 'La rédaction a dépassé son délai. Vous pouvez relancer cette édition sans perdre votre progression.',
  toast_finding_thread: 'Retrouver le fil de votre histoire…',
  toast_in_journey: 'La suite se joue dans la journée du jour.',
  toast_canonical_open: 'L’épisode du jour est ouvert.',
  toast_in_mission: 'La suite se joue dans la mission du jour.',
  toast_resumes: 'L’édition reprend.',
  toast_thread_failed: 'Impossible de retrouver le fil de l’histoire.',
  toast_composing: 'Composition de l’édition. Les planches paraîtront une à une.',
  toast_launched: 'Édition lancée. La lecture reste ouverte pendant le travail de la presse.',
  toast_story_ready: 'Récit prêt. Les planches s’impriment.',
  toast_ready: 'Le Feuilleton est prêt.',
  create_network: 'Le Feuilleton n’a pas pu être créé. Les planches sont peut-être encore sous presse ; réessayez dans un instant.',
  create_incomplete: 'La rédaction n’a pas livré un Feuilleton complet.',
  create_failed: 'Le Feuilleton n’a pas pu être créé.',
  answer_first: 'Écrivez ou choisissez d’abord une réponse.',
  superseded_task: 'Cet épisode a été remplacé ou déjà classé. Votre texte est conservé ; rouvrez l’épisode courant.',
  submit_failed: 'La correction n’a pas pu être transmise. Réessayez.',
  submit_failed_toast: 'La correction du Feuilleton n’a pas pu être transmise.',
  complete_done: 'Feuilleton terminé.',
  complete_failed: 'Le Feuilleton n’a pas pu être terminé.',
  // ---- /graphic-novel: head and actions
  actions_aria: 'Actions de lecture du Feuilleton',
  back_atelier: 'Retour à L’Atelier',
  back_home: 'Retour à La Une',
  back_season: 'Retour à la saison',
  finding_thread: 'Recherche du fil',
  resume_story: 'Reprendre l’histoire',
  loading_sr: 'Ouverture du Feuilleton. Recherche de l’édition en cours. Si aucune n’est prête, un seul bouton permettra de la composer.',
  complete_episode: 'Terminer l’épisode',
  superseded_title: 'Cette édition a été remplacée.',
  superseded_body: 'Votre lecture et vos réponses restent ici. L’épisode courant peut être rouvert quand vous voulez.',
  searching: 'Recherche…',
  reopen_current: 'Rouvrir l’épisode courant',
  head_opening: 'Ouverture de l’épisode…',
  head_notice: 'avis de la rédaction',
  head_failed: 'L’édition n’a pas pu paraître.',
  state_printing: 'impression en cours',
  state_writing: 'rédaction en cours',
  head_printing: 'Les planches s’impriment',
  head_writing: 'L’édition se compose',
  season_n: 'Saison {n}',
  head_today: 'L’épisode du jour',
  head_off_edition: 'hors édition',
  supplement: 'Le supplément illustré',
  episode_n: 'Épisode {n}',
  episode: 'Épisode',
  edition_today: 'Édition du jour',
  next_courrier: 'Agir dans Le Courrier',
  next_episode: 'Lire le prochain épisode',
  // ---- notices around the reader
  art_ready: 'L’histoire est prête.',
  art_progress: 'Les illustrations s’impriment en arrière-plan — {ready} sur {total}.',
  cast_link_aria: 'Relation avec {name} : {register}, proximité {closeness} sur 5',
  cast_link: 'vous vous dites',
  composing_title: 'Composition de l’édition',
  composing_body: 'Écriture du ressort, puis impression de {target}. Les images demandent le plus de temps ; gardez cet écran ouvert, la lecture s’ouvre dès que la scène est prête.',
  target_page: 'la page illustrée',
  target_panels: '{n} planches',
  // ---- the episode tab
  illustration_missing: 'L’illustration de cet épisode n’est pas encore parue.',
  hero_aria: 'Épisode du Feuilleton',
  kicker_pressing: 'sous presse',
  kicker_today: 'aujourd’hui',
  lead_pressing_title: 'L’épisode du jour est sous presse.',
  lead_title: 'L’épisode du jour vous attend.',
  lead_pressing_body: 'La rédaction compose la planche. Rouvrez dans un instant : votre place dans la saison est gardée.',
  cast_episode_aria: 'Personnages de cet épisode',
  cast_act_aria: 'Personnages de cet acte',
  see_progress: 'Voir où en est l’épisode',
  open_today: 'Ouvrir l’épisode du jour',
  kicker_in_seance: 'dans la séance',
  in_seance_title: 'L’épisode du jour se lit dans la séance.',
  open_seance_today: 'Ouvrir la séance du jour',
  delayed_aria: 'Épisode retardé du Feuilleton',
  kicker_delayed: 'retardé',
  press_title: 'Sous presse',
  delayed_body: 'L’épisode est retardé — la rédaction met la planche sous presse.',
  retrying: 'Nouvelle tentative',
  retry: 'Réessayer',
  reread_season: 'Relire la saison',
  filed_aria: 'Épisode classé du Feuilleton',
  kicker_filed: 'classé',
  filed_title: 'L’épisode du jour est classé.',
  filed_body: 'Il a rejoint la saison reliée. La suite paraîtra au prochain épisode.',
  resume_thread: 'Reprendre le fil',
  open_bound_season: 'Ouvrir la saison reliée',
  supplement_aria: 'Supplément illustré du Feuilleton',
  margin: 'En marge',
  composing_now: 'Composition en cours',
  supplement_note: 'Une scène composée à la demande, en marge du feuilleton. Elle ne change rien à la saison.',
  mission_aria: 'Prochain acte du Feuilleton',
  mission_art: 'Votre histoire · maintenant',
  act_now: 'Acte {n} · maintenant',
  mission_title: 'La suite se joue avant de se lire.',
  open_mission: 'Ouvrir la mission du jour',
  mission_small: 'Votre réponse deviendra la conséquence du prochain épisode. Aucun récit parallèle ne sera créé.',
  previously_prefix: 'Précédemment : {text}',
  pressure_marchand: 'Votre message à M. Marchand doit régler le problème de l’appartement. Sa réponse deviendra la première conséquence du Feuilleton.',
  pressure_default: 'Une réponse réelle doit faire avancer la situation. Le prochain épisode montrera exactement ce qu’elle a changé.',
  seed_thread: 'Fil de L’Atelier prêt',
  seed_topic: 'Sujet du jour prêt',
  seed_optional: 'Lecture facultative',
  seed_copy: 'Composez une édition pour une courte pause de lecture. La feuille de tâches n’apparaît qu’avec les planches.',
  empty_aria: 'Feuilleton sans édition',
  empty_title: 'Aucune scène sur le pupitre.',
  locked_title: 'Feuille de tâches verrouillée',
  locked_body: 'Les tâches se déplient sous les planches une fois l’édition composée.',
  compose_aria: 'Composer une nouvelle scène du Feuilleton',
  compose_first: 'Composer la première scène',
  no_plates_title: 'Cette édition est parue sans planche.',
  no_plates_body: 'La rédaction n’a rien livré à lire pour cette scène.',
  filing: 'Classement…',
  // the seeded learning thread
  thread_aria: 'Fil du jour',
  thread_title: 'Scène issue de L’Atelier',
  chip_grammar: 'Grammaire',
  chip_vocabulary: 'Lexique',
  chip_errata: 'Errata',
  chip_mission: 'Mission',
  chip_serial: 'Fil du récit',
  chip_session: 'Séance',
  count_point_one: '{n} point',
  count_point_many: '{n} points',
  count_word_one: '{n} mot',
  count_word_many: '{n} mots',
  count_repair_one: '{n} erratum',
  count_repair_many: '{n} errata',
  source_session: 'la séance',
  source_serial: 'le fil du récit',
  source_mission: 'la mission',
  source_grammar_one: '{n} point de grammaire',
  source_grammar_many: '{n} points de grammaire',
  source_vocabulary_one: '{n} mot de lexique',
  source_vocabulary_many: '{n} mots de lexique',
  source_errata_one: '{n} erratum',
  source_errata_many: '{n} errata',
  source_default: 'L’Atelier',
  and: 'et',
  thread_summary: 'Cette édition est issue de {sources} dans le fil d’apprentissage du jour.',
  // failure and pressing
  failure_default: 'L’édition n’a pas pu être composée. Votre progression n’a pas été modifiée.',
  notice_title: 'Avis de la rédaction',
  relaunching: 'Relance en cours',
  relaunch: 'Relancer l’édition',
  open_cahier: 'Ouvrir Le Cahier',
  writing_aria: 'Édition en préparation',
  plates_printing: 'Les planches sont sous presse.',
  assembling: 'La rédaction assemble le récit.',
  story_ready: 'Le récit est prêt.',
  story_first: 'Le récit arrive d’abord.',
  printing_body: 'Les planches sont en cours d’impression{progress}. Cette page se met à jour automatiquement.',
  printing_progress: ' — {ready} sur {total}',
  writing_body: 'Les planches seront imprimées ensuite. Cette page se met à jour automatiquement.',
  // audio
  panel_audio_failed: 'Cette planche n’a pas pu être lue.',
  listen_panel: 'Écouter la planche {n}',
  episode_audio_failed: 'L’audio de l’épisode n’a pas pu être lu.',
  narrated_one: '{n} planche narrée',
  narrated_many: '{n} planches narrées',
  listen_episode: 'Écouter l’épisode',
  stop_listening: 'Arrêter la lecture',
  playing: 'Lecture en cours',
  // the end
  end_aria: 'Fin de l’épisode',
  filed_state: 'Classé',
  credit_one: 'Un mot de cette édition rejoint votre révision.',
  credit_many: '{n} mots de cette édition rejoignent votre révision.',
  // ---- /serial
  season_opening: 'Ouverture de la saison…',
  season_count_one: 'Saison {season} · {n} épisode paru',
  season_count_many: 'Saison {season} · {n} épisodes parus',
  season_loading: 'Chargement de la saison',
  season_failed_title: 'La saison n’a pas pu être ouverte.',
  season_failed_body: 'La liaison avec la rédaction a échoué. Rien n’est perdu ; réessayez dans un instant.',
  current_aria: 'Épisode en cours',
  hero_fallback: 'La suite de votre histoire vous attend.',
  continue_day: 'Continuer la journée',
  read_reply: 'Lire et répondre',
  generated_aria: 'Épisodes générés',
  status_read: 'lu',
  status_abandoned: 'abandonné',
  status_open: 'en cours',
  episode_filed: 'Épisode classé',
  first_title: 'Le premier numéro n’est pas encore paru.',
  first_body: 'Dès qu’un épisode est lu ou qu’un acte est joué, il se range ici, planche par planche, avec votre réplique.',
  open_first: 'Ouvrir le premier épisode',
  cast_register: 'Le registre du théâtre',
  // ---- /serial/episode/[n]
  replay_aria: 'Relecture de l’épisode',
  replay_kicker: 'Saison {season} · Épisode {n} · relecture',
  replay_loading: 'On tire l’épisode',
  replay_panels_aria: 'Planches de l’épisode',
  plate_alt: 'Planche : {title}',
  plate_missing: 'Cette planche est parue sans illustration.',
  panel_n: 'Planche {n}',
  replay_act_aria: 'L’acte rejoué',
  replay_act: 'L’acte',
  correspondent: 'Votre correspondant',
  you: 'Vous',
  archive_failed_title: 'Les archives n’ont pas répondu.',
  archive_failed_body: 'La connexion a échoué. Rien n’est perdu — l’épisode est classé, pas la page.',
  not_filed_title: 'Épisode non classé.',
  not_filed_body: 'Cette entrée ne figure pas encore aux archives.',
  // ---- /serial/cast
  cast_page_aria: 'Le Feuilleton · les personnages',
  cast_one_tu: 'Le registre du théâtre · un tutoiement accordé',
  cast_all_vous: 'Le registre du théâtre · tout le monde vous vouvoie encore',
  cast_loading: 'On appelle les rôles',
  your_character: 'Votre personnage',
  avatar_visible: 'Avatar visible',
  pov_mode: 'Mode POV',
  sheet_avatar: 'Fiche privée · style verrouillé',
  sheet_pov: 'Fiche privée · POV, jamais dessiné',
  close: 'Fermer',
  customise: 'Personnaliser',
  descriptor: 'Descripteur visuel',
  descriptor_placeholder: 'ex. écharpe rouge, carnet',
  saving: 'Enregistrement…',
  use_avatar: 'Utiliser l’avatar',
  stay_pov: 'Rester en POV',
  avatar_saved: 'Avatar retenu pour les prochaines planches.',
  pov_saved: 'Mode POV enregistré.',
  avatar_failed: 'Impossible d’enregistrer votre personnage.',
  register_granted: 'accordé',
  register_formal: 'de rigueur',
  closeness: 'Proximité',
  closeness_aria: 'Proximité {n} sur 5',
  tu_since: 'Tutoiement — ép. {n}',
  no_tu: 'Pas encore de tutoiement',
  mood_m2: '{name} vous en veut encore.',
  mood_m1: '{name} garde un peu ses distances.',
  mood_p1: '{name} vous sourit volontiers.',
  mood_p2: '{name} se réjouit de vous voir.',
  callbacks: 'Rappels',
  no_callbacks: 'Aucun rappel encore — l’histoire commence.',
  last_exchange: 'Dernier échange —',
  never_spoke: 'Vous ne vous êtes pas encore parlé.',
  // ---- the season page (WP-44)
  season_headline: 'La saison jusqu’ici',
  open_seance: 'Ouvrir la séance',
  commitment_one: 'Engagement en cours',
  commitment_many: 'Engagements en cours',
  season_threads: 'Les fils de la saison',
  thread_open: 'en suspens',
  thread_developing: 'ça bouge',
  thread_closed: 'réglé',
  season_empty: 'Votre première scène s’ouvre dans la séance.',
  chapter_n: 'chapitre {n}',
  season_today: 'Aujourd’hui · épisode {n} · se joue dans la séance',
  with_character: 'avec {name}',
};

export type FeuilletonCopy = { [K in keyof typeof FR]: string };

const EN: FeuilletonCopy = {
  lang: 'en',
  feuilleton: 'Le Feuilleton',
  gen_failed: 'The episode could not be put together.',
  scene_unavailable: 'The episode’s page could not be opened. Try composing it again.',
  gen_stalled: 'Writing took longer than it should. You can start this episode again without losing your progress.',
  toast_finding_thread: 'Finding where your story left off…',
  toast_in_journey: 'The story continues in today’s session.',
  toast_canonical_open: 'Today’s episode is open.',
  toast_in_mission: 'The story continues in today’s letter.',
  toast_resumes: 'The episode picks up again.',
  toast_thread_failed: 'Your story could not be found.',
  toast_composing: 'Putting the episode together. The panels will appear one by one.',
  toast_launched: 'Episode started. You can keep reading while the panels are drawn.',
  toast_story_ready: 'Story ready. The panels are being drawn.',
  toast_ready: 'Your episode is ready.',
  create_network: 'The episode could not be created. The panels may still be printing; try again in a moment.',
  create_incomplete: 'The episode came back incomplete.',
  create_failed: 'The episode could not be created.',
  answer_first: 'Write or choose an answer first.',
  superseded_task: 'This episode has been replaced or already filed. Your text is kept; reopen the current episode.',
  submit_failed: 'Your answer could not be sent. Try again.',
  submit_failed_toast: 'Your answer could not be sent.',
  complete_done: 'Episode finished.',
  complete_failed: 'The episode could not be finished.',
  actions_aria: 'Reading actions',
  back_atelier: 'Back to L’Atelier',
  back_home: 'Back to La Une',
  back_season: 'Back to the season',
  finding_thread: 'Finding your story',
  resume_story: 'Pick up the story',
  loading_sr: 'Opening Le Feuilleton. Looking for your episode. If none is ready, one button will let you compose it.',
  complete_episode: 'Finish the episode',
  superseded_title: 'This episode has been replaced.',
  superseded_body: 'Your reading and your answers stay here. You can reopen the current episode whenever you like.',
  searching: 'Searching…',
  reopen_current: 'Reopen the current episode',
  head_opening: 'Opening the episode…',
  head_notice: 'a note from the editors',
  head_failed: 'The episode could not be published.',
  state_printing: 'printing',
  state_writing: 'being written',
  head_printing: 'The panels are printing',
  head_writing: 'The episode is being written',
  season_n: 'Season {n}',
  head_today: 'Today’s episode',
  head_off_edition: 'extra',
  supplement: 'The illustrated extra',
  episode_n: 'Episode {n}',
  episode: 'Episode',
  edition_today: 'Today’s edition',
  next_courrier: 'Reply in Le Courrier',
  next_episode: 'Read the next episode',
  art_ready: 'The story is ready.',
  art_progress: 'The pictures are printing in the background — {ready} of {total}.',
  cast_link_aria: 'Your relationship with {name}: {register}, closeness {closeness} of 5',
  cast_link: 'you say',
  composing_title: 'Putting the episode together',
  composing_body: 'Writing the story, then printing {target}. The pictures take the longest; keep this screen open, reading opens as soon as the scene is ready.',
  target_page: 'the illustrated page',
  target_panels: '{n} panels',
  illustration_missing: 'This episode’s picture has not come out yet.',
  hero_aria: 'Feuilleton episode',
  kicker_pressing: 'printing',
  kicker_today: 'today',
  lead_pressing_title: 'Today’s episode is being printed.',
  lead_title: 'Today’s episode is waiting for you.',
  lead_pressing_body: 'The panel is being drawn. Come back in a moment: your place in the season is kept.',
  cast_episode_aria: 'Characters in this episode',
  cast_act_aria: 'Characters in this act',
  see_progress: 'See how the episode is doing',
  open_today: 'Open today’s episode',
  kicker_in_seance: 'in the session',
  in_seance_title: 'Today’s episode is read in the session.',
  open_seance_today: 'Open today’s session',
  delayed_aria: 'Delayed episode',
  kicker_delayed: 'delayed',
  press_title: 'Printing',
  delayed_body: 'The episode is delayed — its panel is still being printed.',
  retrying: 'Trying again',
  retry: 'Try again',
  reread_season: 'Read the season again',
  filed_aria: 'Filed episode',
  kicker_filed: 'filed',
  filed_title: 'Today’s episode is filed.',
  filed_body: 'It has joined the bound season. The story continues in the next episode.',
  resume_thread: 'Pick up the story',
  open_bound_season: 'Open the bound season',
  supplement_aria: 'Illustrated extra',
  margin: 'On the side',
  composing_now: 'Being composed',
  supplement_note: 'A scene made on request, on the side of the story. It changes nothing in the season.',
  mission_aria: 'Next act',
  mission_art: 'Your story · now',
  act_now: 'Act {n} · now',
  mission_title: 'The next part is played before it is read.',
  open_mission: 'Open today’s letter',
  mission_small: 'Your reply becomes what happens in the next episode. No parallel story is created.',
  previously_prefix: 'Previously: {text}',
  pressure_marchand: 'Your message to M. Marchand has to sort out the flat. His reply becomes the first consequence in Le Feuilleton.',
  pressure_default: 'A real answer has to move the situation on. The next episode shows exactly what it changed.',
  seed_thread: 'Thread from L’Atelier ready',
  seed_topic: 'Today’s topic ready',
  seed_optional: 'Optional reading',
  seed_copy: 'Compose an episode for a short reading break. The tasks only appear with the panels.',
  empty_aria: 'No episode yet',
  empty_title: 'No scene on the desk.',
  locked_title: 'Tasks locked',
  locked_body: 'The tasks unfold under the panels once the episode is composed.',
  compose_aria: 'Compose a new scene',
  compose_first: 'Compose the first scene',
  no_plates_title: 'This episode came out without any panels.',
  no_plates_body: 'Nothing was delivered to read for this scene.',
  filing: 'Filing…',
  thread_aria: 'Today’s thread',
  thread_title: 'A scene from L’Atelier',
  chip_grammar: 'Grammar',
  chip_vocabulary: 'Lexique',
  chip_errata: 'Corrections',
  chip_mission: 'Letter',
  chip_serial: 'Story thread',
  chip_session: 'Session',
  count_point_one: '{n} point',
  count_point_many: '{n} points',
  count_word_one: '{n} word',
  count_word_many: '{n} words',
  count_repair_one: '{n} correction',
  count_repair_many: '{n} corrections',
  source_session: 'the session',
  source_serial: 'the story thread',
  source_mission: 'the letter',
  source_grammar_one: '{n} grammar point',
  source_grammar_many: '{n} grammar points',
  source_vocabulary_one: '{n} word',
  source_vocabulary_many: '{n} words',
  source_errata_one: '{n} correction',
  source_errata_many: '{n} corrections',
  source_default: 'L’Atelier',
  and: 'and',
  thread_summary: 'This episode comes from {sources} in today’s learning thread.',
  failure_default: 'The episode could not be put together. Your progress has not changed.',
  notice_title: 'A note from the editors',
  relaunching: 'Starting again',
  relaunch: 'Start the episode again',
  open_cahier: 'Open Le Cahier',
  writing_aria: 'Episode in preparation',
  plates_printing: 'The panels are printing.',
  assembling: 'The story is being put together.',
  story_ready: 'The story is ready.',
  story_first: 'The story comes first.',
  printing_body: 'The panels are printing{progress}. This page updates by itself.',
  printing_progress: ' — {ready} of {total}',
  writing_body: 'The panels are printed next. This page updates by itself.',
  panel_audio_failed: 'This panel could not be played.',
  listen_panel: 'Listen to panel {n}',
  episode_audio_failed: 'The episode’s audio could not be played.',
  narrated_one: '{n} narrated panel',
  narrated_many: '{n} narrated panels',
  listen_episode: 'Listen to the episode',
  stop_listening: 'Stop listening',
  playing: 'Playing',
  end_aria: 'End of the episode',
  filed_state: 'Filed',
  credit_one: 'One word from this episode joins your review.',
  credit_many: '{n} words from this episode join your review.',
  season_opening: 'Opening the season…',
  season_count_one: 'Season {season} · {n} episode out',
  season_count_many: 'Season {season} · {n} episodes out',
  season_loading: 'Loading the season',
  season_failed_title: 'The season could not be opened.',
  season_failed_body: 'The connection failed. Nothing is lost; try again in a moment.',
  current_aria: 'Current episode',
  hero_fallback: 'The next part of your story is waiting.',
  continue_day: 'Continue today',
  read_reply: 'Read and reply',
  generated_aria: 'Your episodes',
  status_read: 'read',
  status_abandoned: 'left',
  status_open: 'in progress',
  episode_filed: 'Filed episode',
  first_title: 'The first episode is not out yet.',
  first_body: 'As soon as you read an episode or play an act, it is kept here, panel by panel, with your reply.',
  open_first: 'Open the first episode',
  cast_register: 'The cast',
  replay_aria: 'Reading the episode again',
  replay_kicker: 'Season {season} · Episode {n} · reread',
  replay_loading: 'Fetching the episode',
  replay_panels_aria: 'The episode’s panels',
  plate_alt: 'Panel: {title}',
  plate_missing: 'This panel came out without a picture.',
  panel_n: 'Panel {n}',
  replay_act_aria: 'The act, replayed',
  replay_act: 'The act',
  correspondent: 'Your correspondent',
  you: 'You',
  archive_failed_title: 'The archive did not answer.',
  archive_failed_body: 'The connection failed. Nothing is lost — the episode is filed, only the page did not load.',
  not_filed_title: 'Episode not filed.',
  not_filed_body: 'This entry is not in the archive yet.',
  cast_page_aria: 'Le Feuilleton · the characters',
  cast_one_tu: 'The cast · someone now says «tu» to you',
  cast_all_vous: 'The cast · everyone still says «vous» to you',
  cast_loading: 'Calling the cast',
  your_character: 'Your character',
  avatar_visible: 'Avatar shown',
  pov_mode: 'First-person view',
  sheet_avatar: 'Private sheet · style locked',
  sheet_pov: 'Private sheet · first person, never drawn',
  close: 'Close',
  customise: 'Customise',
  descriptor: 'How you look',
  descriptor_placeholder: 'e.g. red scarf, notebook',
  saving: 'Saving…',
  use_avatar: 'Use the avatar',
  stay_pov: 'Stay in first person',
  avatar_saved: 'Avatar kept for the next panels.',
  pov_saved: 'First-person view saved.',
  avatar_failed: 'Your character could not be saved.',
  register_granted: 'granted',
  register_formal: 'still formal',
  closeness: 'Closeness',
  closeness_aria: 'Closeness {n} of 5',
  tu_since: '«tu» since ep. {n}',
  no_tu: 'Not on «tu» terms yet',
  mood_m2: '{name} still holds it against you.',
  mood_m1: '{name} is keeping a little distance.',
  mood_p1: '{name} is happy to smile at you.',
  mood_p2: '{name} is delighted to see you.',
  callbacks: 'Remembered',
  no_callbacks: 'Nothing remembered yet — the story is starting.',
  last_exchange: 'Last exchange —',
  never_spoke: 'You have not spoken yet.',
  season_headline: 'The season so far',
  open_seance: 'Open the session',
  commitment_one: 'Open promise',
  commitment_many: 'Open promises',
  season_threads: 'The season’s threads',
  thread_open: 'open',
  thread_developing: 'moving',
  thread_closed: 'settled',
  season_empty: 'Your first scene opens in the session.',
  chapter_n: 'chapter {n}',
  season_today: 'Today · episode {n} · played in the session',
  with_character: 'with {name}',
};

const DE: FeuilletonCopy = {
  lang: 'de',
  feuilleton: 'Le Feuilleton',
  gen_failed: 'Die Folge konnte nicht erstellt werden.',
  scene_unavailable: 'Die Seite der Folge ließ sich nicht öffnen. Erstelle die Folge noch einmal.',
  gen_stalled: 'Das Schreiben hat zu lange gedauert. Du kannst die Folge neu starten, ohne deinen Fortschritt zu verlieren.',
  toast_finding_thread: 'Deine Geschichte wird gesucht…',
  toast_in_journey: 'Die Geschichte geht in der heutigen Sitzung weiter.',
  toast_canonical_open: 'Die heutige Folge ist geöffnet.',
  toast_in_mission: 'Die Geschichte geht im heutigen Brief weiter.',
  toast_resumes: 'Die Folge geht weiter.',
  toast_thread_failed: 'Deine Geschichte wurde nicht gefunden.',
  toast_composing: 'Die Folge wird erstellt. Die Bilder erscheinen nacheinander.',
  toast_launched: 'Folge gestartet. Du kannst weiterlesen, während die Bilder gezeichnet werden.',
  toast_story_ready: 'Geschichte fertig. Die Bilder werden gezeichnet.',
  toast_ready: 'Deine Folge ist fertig.',
  create_network: 'Die Folge konnte nicht erstellt werden. Vielleicht werden die Bilder noch gedruckt; versuche es gleich noch einmal.',
  create_incomplete: 'Die Folge kam unvollständig zurück.',
  create_failed: 'Die Folge konnte nicht erstellt werden.',
  answer_first: 'Schreib oder wähle zuerst eine Antwort.',
  superseded_task: 'Diese Folge wurde ersetzt oder schon abgelegt. Dein Text bleibt erhalten; öffne die aktuelle Folge erneut.',
  submit_failed: 'Deine Antwort konnte nicht gesendet werden. Versuche es noch einmal.',
  submit_failed_toast: 'Deine Antwort konnte nicht gesendet werden.',
  complete_done: 'Folge beendet.',
  complete_failed: 'Die Folge konnte nicht beendet werden.',
  actions_aria: 'Aktionen zum Lesen',
  back_atelier: 'Zurück zu L’Atelier',
  back_home: 'Zurück zu La Une',
  back_season: 'Zurück zur Staffel',
  finding_thread: 'Geschichte wird gesucht',
  resume_story: 'Geschichte fortsetzen',
  loading_sr: 'Le Feuilleton wird geöffnet. Deine Folge wird gesucht. Ist keine fertig, kannst du sie mit einem Knopf erstellen.',
  complete_episode: 'Folge beenden',
  superseded_title: 'Diese Folge wurde ersetzt.',
  superseded_body: 'Dein Lesestand und deine Antworten bleiben hier. Du kannst die aktuelle Folge jederzeit wieder öffnen.',
  searching: 'Wird gesucht…',
  reopen_current: 'Aktuelle Folge wieder öffnen',
  head_opening: 'Die Folge wird geöffnet…',
  head_notice: 'Hinweis der Redaktion',
  head_failed: 'Die Folge konnte nicht erscheinen.',
  state_printing: 'wird gedruckt',
  state_writing: 'wird geschrieben',
  head_printing: 'Die Bilder werden gedruckt',
  head_writing: 'Die Folge wird geschrieben',
  season_n: 'Staffel {n}',
  head_today: 'Die Folge von heute',
  head_off_edition: 'Extra',
  supplement: 'Das illustrierte Extra',
  episode_n: 'Folge {n}',
  episode: 'Folge',
  edition_today: 'Ausgabe von heute',
  next_courrier: 'In Le Courrier antworten',
  next_episode: 'Nächste Folge lesen',
  art_ready: 'Die Geschichte ist fertig.',
  art_progress: 'Die Bilder werden im Hintergrund gedruckt — {ready} von {total}.',
  cast_link_aria: 'Deine Beziehung zu {name}: {register}, Nähe {closeness} von 5',
  cast_link: 'ihr sagt',
  composing_title: 'Die Folge wird erstellt',
  composing_body: 'Erst wird die Geschichte geschrieben, dann {target} gedruckt. Die Bilder dauern am längsten; lass diesen Bildschirm offen, das Lesen beginnt, sobald die Szene fertig ist.',
  target_page: 'die illustrierte Seite',
  target_panels: '{n} Bilder',
  illustration_missing: 'Das Bild zu dieser Folge ist noch nicht erschienen.',
  hero_aria: 'Folge aus Le Feuilleton',
  kicker_pressing: 'im Druck',
  kicker_today: 'heute',
  lead_pressing_title: 'Die Folge von heute wird gedruckt.',
  lead_title: 'Die Folge von heute wartet auf dich.',
  lead_pressing_body: 'Das Bild wird gerade gezeichnet. Schau gleich wieder vorbei: dein Platz in der Staffel bleibt erhalten.',
  cast_episode_aria: 'Figuren in dieser Folge',
  cast_act_aria: 'Figuren in diesem Akt',
  see_progress: 'Stand der Folge ansehen',
  open_today: 'Folge von heute öffnen',
  kicker_in_seance: 'in der Sitzung',
  in_seance_title: 'Die Folge von heute liest du in der Sitzung.',
  open_seance_today: 'Heutige Sitzung öffnen',
  delayed_aria: 'Verspätete Folge',
  kicker_delayed: 'verspätet',
  press_title: 'Im Druck',
  delayed_body: 'Die Folge ist verspätet — ihr Bild wird noch gedruckt.',
  retrying: 'Neuer Versuch',
  retry: 'Noch einmal versuchen',
  reread_season: 'Staffel noch einmal lesen',
  filed_aria: 'Abgelegte Folge',
  kicker_filed: 'abgelegt',
  filed_title: 'Die Folge von heute ist abgelegt.',
  filed_body: 'Sie gehört jetzt zur gebundenen Staffel. Die Geschichte geht in der nächsten Folge weiter.',
  resume_thread: 'Geschichte fortsetzen',
  open_bound_season: 'Gebundene Staffel öffnen',
  supplement_aria: 'Illustriertes Extra',
  margin: 'Am Rand',
  composing_now: 'Wird erstellt',
  supplement_note: 'Eine Szene auf Wunsch, am Rand der Geschichte. Sie ändert nichts an der Staffel.',
  mission_aria: 'Nächster Akt',
  mission_art: 'Deine Geschichte · jetzt',
  act_now: 'Akt {n} · jetzt',
  mission_title: 'Der nächste Teil wird gespielt, bevor man ihn liest.',
  open_mission: 'Heutigen Brief öffnen',
  mission_small: 'Deine Antwort wird zur Folge in der nächsten Episode. Es entsteht keine Parallelgeschichte.',
  previously_prefix: 'Bisher: {text}',
  pressure_marchand: 'Deine Nachricht an M. Marchand muss das Problem mit der Wohnung lösen. Seine Antwort wird die erste Folge in Le Feuilleton.',
  pressure_default: 'Eine echte Antwort muss die Lage voranbringen. Die nächste Folge zeigt genau, was sie verändert hat.',
  seed_thread: 'Faden aus L’Atelier bereit',
  seed_topic: 'Thema des Tages bereit',
  seed_optional: 'Freiwillige Lektüre',
  seed_copy: 'Erstelle eine Folge für eine kurze Lesepause. Die Aufgaben erscheinen erst mit den Bildern.',
  empty_aria: 'Noch keine Folge',
  empty_title: 'Keine Szene auf dem Tisch.',
  locked_title: 'Aufgaben gesperrt',
  locked_body: 'Die Aufgaben erscheinen unter den Bildern, sobald die Folge erstellt ist.',
  compose_aria: 'Neue Szene erstellen',
  compose_first: 'Erste Szene erstellen',
  no_plates_title: 'Diese Folge ist ohne Bilder erschienen.',
  no_plates_body: 'Für diese Szene wurde nichts zum Lesen geliefert.',
  filing: 'Wird abgelegt…',
  thread_aria: 'Faden des Tages',
  thread_title: 'Eine Szene aus L’Atelier',
  chip_grammar: 'Grammatik',
  chip_vocabulary: 'Lexique',
  chip_errata: 'Korrekturen',
  chip_mission: 'Brief',
  chip_serial: 'Erzählfaden',
  chip_session: 'Sitzung',
  count_point_one: '{n} Punkt',
  count_point_many: '{n} Punkte',
  count_word_one: '{n} Wort',
  count_word_many: '{n} Wörter',
  count_repair_one: '{n} Korrektur',
  count_repair_many: '{n} Korrekturen',
  source_session: 'der Sitzung',
  source_serial: 'dem Erzählfaden',
  source_mission: 'dem Brief',
  source_grammar_one: '{n} Grammatikpunkt',
  source_grammar_many: '{n} Grammatikpunkten',
  source_vocabulary_one: '{n} Wort',
  source_vocabulary_many: '{n} Wörtern',
  source_errata_one: '{n} Korrektur',
  source_errata_many: '{n} Korrekturen',
  source_default: 'L’Atelier',
  and: 'und',
  thread_summary: 'Diese Folge entsteht aus {sources} im heutigen Lernfaden.',
  failure_default: 'Die Folge konnte nicht erstellt werden. Dein Fortschritt hat sich nicht verändert.',
  notice_title: 'Hinweis der Redaktion',
  relaunching: 'Wird neu gestartet',
  relaunch: 'Folge neu starten',
  open_cahier: 'Le Cahier öffnen',
  writing_aria: 'Folge in Vorbereitung',
  plates_printing: 'Die Bilder werden gedruckt.',
  assembling: 'Die Geschichte wird zusammengesetzt.',
  story_ready: 'Die Geschichte ist fertig.',
  story_first: 'Zuerst kommt die Geschichte.',
  printing_body: 'Die Bilder werden gedruckt{progress}. Diese Seite aktualisiert sich von selbst.',
  printing_progress: ' — {ready} von {total}',
  writing_body: 'Danach werden die Bilder gedruckt. Diese Seite aktualisiert sich von selbst.',
  panel_audio_failed: 'Dieses Bild konnte nicht abgespielt werden.',
  listen_panel: 'Bild {n} anhören',
  episode_audio_failed: 'Der Ton der Folge konnte nicht abgespielt werden.',
  narrated_one: '{n} vertontes Bild',
  narrated_many: '{n} vertonte Bilder',
  listen_episode: 'Folge anhören',
  stop_listening: 'Wiedergabe stoppen',
  playing: 'Wird abgespielt',
  end_aria: 'Ende der Folge',
  filed_state: 'Abgelegt',
  credit_one: 'Ein Wort aus dieser Folge kommt in deine Wiederholung.',
  credit_many: '{n} Wörter aus dieser Folge kommen in deine Wiederholung.',
  season_opening: 'Die Staffel wird geöffnet…',
  season_count_one: 'Staffel {season} · {n} Folge erschienen',
  season_count_many: 'Staffel {season} · {n} Folgen erschienen',
  season_loading: 'Staffel wird geladen',
  season_failed_title: 'Die Staffel ließ sich nicht öffnen.',
  season_failed_body: 'Die Verbindung ist fehlgeschlagen. Nichts ist verloren; versuche es gleich noch einmal.',
  current_aria: 'Aktuelle Folge',
  hero_fallback: 'Der nächste Teil deiner Geschichte wartet.',
  continue_day: 'Heute weitermachen',
  read_reply: 'Lesen und antworten',
  generated_aria: 'Deine Folgen',
  status_read: 'gelesen',
  status_abandoned: 'abgebrochen',
  status_open: 'läuft',
  episode_filed: 'Abgelegte Folge',
  first_title: 'Die erste Folge ist noch nicht erschienen.',
  first_body: 'Sobald du eine Folge liest oder einen Akt spielst, wird sie hier abgelegt, Bild für Bild, mit deiner Antwort.',
  open_first: 'Erste Folge öffnen',
  cast_register: 'Die Figuren',
  replay_aria: 'Folge noch einmal lesen',
  replay_kicker: 'Staffel {season} · Folge {n} · noch einmal gelesen',
  replay_loading: 'Die Folge wird geholt',
  replay_panels_aria: 'Die Bilder der Folge',
  plate_alt: 'Bild: {title}',
  plate_missing: 'Dieses Bild ist ohne Illustration erschienen.',
  panel_n: 'Bild {n}',
  replay_act_aria: 'Der Akt, noch einmal gespielt',
  replay_act: 'Der Akt',
  correspondent: 'Dein Gegenüber',
  you: 'Du',
  archive_failed_title: 'Das Archiv hat nicht geantwortet.',
  archive_failed_body: 'Die Verbindung ist fehlgeschlagen. Nichts ist verloren — die Folge ist abgelegt, nur die Seite hat nicht geladen.',
  not_filed_title: 'Folge nicht abgelegt.',
  not_filed_body: 'Dieser Eintrag ist noch nicht im Archiv.',
  cast_page_aria: 'Le Feuilleton · die Figuren',
  cast_one_tu: 'Die Figuren · jemand duzt dich jetzt («tu»)',
  cast_all_vous: 'Die Figuren · alle siezen dich noch («vous»)',
  cast_loading: 'Die Figuren werden gerufen',
  your_character: 'Deine Figur',
  avatar_visible: 'Avatar sichtbar',
  pov_mode: 'Ich-Perspektive',
  sheet_avatar: 'Privates Blatt · Stil festgelegt',
  sheet_pov: 'Privates Blatt · Ich-Perspektive, nie gezeichnet',
  close: 'Schließen',
  customise: 'Anpassen',
  descriptor: 'Wie du aussiehst',
  descriptor_placeholder: 'z. B. roter Schal, Notizbuch',
  saving: 'Wird gespeichert…',
  use_avatar: 'Avatar verwenden',
  stay_pov: 'In der Ich-Perspektive bleiben',
  avatar_saved: 'Avatar für die nächsten Bilder übernommen.',
  pov_saved: 'Ich-Perspektive gespeichert.',
  avatar_failed: 'Deine Figur konnte nicht gespeichert werden.',
  register_granted: 'angeboten',
  register_formal: 'noch förmlich',
  closeness: 'Nähe',
  closeness_aria: 'Nähe {n} von 5',
  tu_since: '«tu» seit Folge {n}',
  no_tu: 'Noch kein «tu»',
  mood_m2: '{name} ist dir noch böse.',
  mood_m1: '{name} hält etwas Abstand.',
  mood_p1: '{name} lächelt dich gern an.',
  mood_p2: '{name} freut sich, dich zu sehen.',
  callbacks: 'Erinnerungen',
  no_callbacks: 'Noch keine Erinnerungen — die Geschichte beginnt.',
  last_exchange: 'Letzter Austausch —',
  never_spoke: 'Ihr habt noch nicht miteinander gesprochen.',
  season_headline: 'Die Staffel bisher',
  open_seance: 'Sitzung öffnen',
  commitment_one: 'Offenes Versprechen',
  commitment_many: 'Offene Versprechen',
  season_threads: 'Die Fäden der Staffel',
  thread_open: 'offen',
  thread_developing: 'in Bewegung',
  thread_closed: 'geklärt',
  season_empty: 'Deine erste Szene öffnet sich in der Sitzung.',
  chapter_n: 'Kapitel {n}',
  season_today: 'Heute · Folge {n} · wird in der Sitzung gespielt',
  with_character: 'mit {name}',
};

const TABLES: Record<ControlLanguage, FeuilletonCopy> = { en: EN, de: DE, fr: FR as FeuilletonCopy };

/** The Feuilleton pages' chrome in the language `chromeLanguage()` resolved.
 *  No language (a caller that predates the rule) keeps the French table. */
export function feuilletonCopy(language?: unknown): FeuilletonCopy {
  if (language === null || language === undefined || language === '') return TABLES.fr;
  return TABLES[normalizeControlLanguage(language)];
}

/** `{name}`-style placeholders filled in; an unknown key is left as written. */
export function fbFill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in values ? String(values[key]) : match));
}

type PluralStem =
  | 'season_count'
  | 'count_point'
  | 'count_word'
  | 'count_repair'
  | 'source_grammar'
  | 'source_vocabulary'
  | 'source_errata'
  | 'narrated'
  | 'credit'
  | 'commitment';

/** One of a `_one` / `_many` pair, by count. */
export function fbPlural(copy: FeuilletonCopy, stem: PluralStem, n: number, extra: Record<string, string | number> = {}): string {
  const key = `${stem}_${n === 1 ? 'one' : 'many'}` as keyof FeuilletonCopy;
  return fbFill(copy[key], { n, ...extra });
}

/** «a, b et c» in the table's language. */
export function fbJoin(copy: FeuilletonCopy, items: string[]): string {
  if (items.length <= 1) return items[0] || copy.source_default;
  return `${items.slice(0, -1).join(', ')} ${copy.and} ${items[items.length - 1]}`;
}

export default feuilletonCopy;
