#!/usr/bin/env python3
"""WP-S8 — the simulation baseline: today's ladder against La Forge.

Runs the WP-L3 / WP-S3 simulation (:func:`app.core.srs.simulation.simulate_items_to_held`)
on the same simulated learner for both engines, at 70 / 85 / 95 % accuracy, for
each rhythm (its intake quota and its séance budget), and prints one Markdown
table per scenario:

* **with the journey's Rappel** — the real day: the journey introduces rules at
  the rhythm's quota and poses one Rappel item a day per due rule; the séance
  is either the old fixed ladder (same intake: no padding with new rules) or
  the forge;
* **séance only** — no Rappel, to isolate what the séance itself does.

Columns: median items-to-held and median days-to-held over the judged rules
(introduced ≥ 45 days before the 150-day horizon; a never-held rule counts as
∞ items), and the rules held by day 60 and day 120 of the learner's life,
out of the rules introduced by then.

Usage::

    venv/bin/python scripts/forge_speed_report.py              # print
    venv/bin/python scripts/forge_speed_report.py --write-doc  # also update the WP doc

``--write-doc`` replaces the block between the ``forge-speed-report`` markers in
``docs/implementation/atelier-v2/WORK-PACKAGES-2026-09-24-seance.md``.
"""
from __future__ import annotations

import argparse
import math
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.core.forge import SEANCE_SECONDS_BY_RHYTHM  # noqa: E402
from app.core.srs.simulation import simulate_items_to_held  # noqa: E402
from app.services.concept_life import NEW_CONCEPTS_PER_WEEK  # noqa: E402

DOC = ROOT / "docs/implementation/atelier-v2/WORK-PACKAGES-2026-09-24-seance.md"
BEGIN = "<!-- forge-speed-report:begin -->"
END = "<!-- forge-speed-report:end -->"
ACCURACIES = (0.70, 0.85, 0.95)
RHYTHMS = ("leger", "regulier", "soutenu", "intensif")
RHYTHM_NAMES = {"leger": "Léger", "regulier": "Régulier", "soutenu": "Soutenu", "intensif": "Intensif"}
DAYS = 150


def _introduced_by(day: int, per_week: float) -> int:
    return math.floor(day * per_week / 7.0 + 1e-9)


def _fmt_median(value: float) -> str:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return "—"
    if math.isinf(value):
        return "∞"
    return f"{value:g}"


def run(rappel: bool) -> list[dict]:
    rows = []
    for rhythm in RHYTHMS:
        per_week = float(NEW_CONCEPTS_PER_WEEK[rhythm])
        seconds = SEANCE_SECONDS_BY_RHYTHM[rhythm]
        for accuracy in ACCURACIES:
            for engine in ("ladder", "forge"):
                kwargs = {"ladder_padding": False} if engine == "ladder" else {}
                result = simulate_items_to_held(
                    accuracy,
                    engine=engine,
                    days=DAYS,
                    units_per_week=per_week,
                    seance_seconds=seconds,
                    rappel=rappel,
                    **kwargs,
                )
                rows.append(
                    {
                        "rhythm": rhythm,
                        "accuracy": accuracy,
                        "engine": engine,
                        "items": result.median_items_to_held,
                        "days": result.median_days_to_held,
                        "held": len(result.items_to_held),
                        "judged": result.rules_judged,
                        "held_60": result.held_within(60),
                        "held_120": result.held_within(120),
                        "intro_60": _introduced_by(60, per_week),
                        "intro_120": _introduced_by(120, per_week),
                    }
                )
    return rows


def table(rows: list[dict]) -> str:
    lines = [
        "| Rhythm | Accuracy | Engine | Median items to held | Median days to held | Held / judged | Held by day 60 | Held by day 120 |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        engine = "**Forge**" if row["engine"] == "forge" else "Old ladder"
        lines.append(
            f"| {RHYTHM_NAMES[row['rhythm']]} | {int(row['accuracy'] * 100)} % | {engine} "
            f"| {_fmt_median(row['items'])} | {_fmt_median(row['days'])} | {row['held']} / {row['judged']} "
            f"| {row['held_60']} / {row['intro_60']} | {row['held_120']} / {row['intro_120']} |"
        )
    return "\n".join(lines)


def report() -> str:
    started = time.perf_counter()
    with_rappel = run(rappel=True)
    seance_only = run(rappel=False)
    elapsed = time.perf_counter() - started
    return "\n".join(
        [
            BEGIN,
            f"_Generated by `scripts/forge_speed_report.py` ({elapsed:.1f} s; 150 simulated days, one séance a day, "
            "25 s per item; rules judged if introduced ≥ 45 days before the end; «held by day N» counts rules held "
            "out of rules introduced by then)._",
            "",
            "**With the journey's Rappel (the real day), same intake for both engines:**",
            "",
            table(with_rappel),
            "",
            "**Séance only (no Rappel):**",
            "",
            table(seance_only),
            END,
        ]
    )


def write_doc(block: str) -> None:
    text = DOC.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _old, tail = rest.split(END, 1)
        text = head + block + tail
    else:
        raise SystemExit(f"markers {BEGIN} … {END} not found in {DOC}")
    DOC.write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write-doc", action="store_true", help="update the WP-S8 Status in the séance WP doc")
    args = parser.parse_args()
    block = report()
    print(block)
    if args.write_doc:
        write_doc(block)


if __name__ == "__main__":
    main()
