name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: language_learning
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/language_learning
      REDIS_URL: redis://localhost:6379/0
      CELERY_BROKER_URL: redis://localhost:6379/1
      CELERY_RESULT_BACKEND: redis://localhost:6379/1
      SECRET_KEY: ci-secret-key

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          python -m spacy download fr_core_news_sm

      - name: Lint with ruff
        run: ruff check .

      - name: Run unit tests
        run: pytest --cov=app --cov-report=term-missing

      - name: Verify Alembic migrations
        run: |
          alembic upgrade head
          alembic downgrade base
          alembic upgrade head

      - name: Build Docker image
        run: docker build . -t conversational-language-learning:ci
